### ISSUE TITLE
Removed "search keyword" appears in autocomplition

### ISSUE THREAD

**Issue by dimitrove** [shopizer-ecommerce/shopizer#113]
I had to a product a "search keyword" - "dumbbell". I removed it and I added another one - "weights".
The new one appears in autocomplition - which is fine. But the removed one keeps appearing in autocomplition as well.

Is this a bug or is there a way to rebuild the indexes?

**Comment by dimitrove** [comment]
There are two indexes
- product_en_default - where entries are added/updated/deleted and
- keyword_en_default - where entries are only added on every product update

there is in
sm-search\src\main\java\com\shopizer\search\services\worker\KeywordIndexerImpl.java

	//delete previous keywords for the same id
	//deleteKeywordsImpl.deleteObject(client, collectionName, id);
	deleteKeywordsImpl.deleteObject(client, conf.getCollectionName(), conf.getIndexName(), id);

	//searchDelegate.bulkIndexKeywords(bulks, collectionName, "keyword");
	searchDelegate.bulkIndexKeywords(bulks, conf.getCollectionName(), conf.getIndexName());

May be the "delete" part does not work . . .

**Comment by shopizer-ecommerce** [comment]
You can re-index or use elastic search sense to manage entry in keyword and product index
