### ISSUE TITLE
java.lang.ClassNotFoundException: ShippingQuotePrePostProcessModule Java7-Tomcat7-ShopizerV2.0.3

### ISSUE THREAD

**Issue by itskoolsid** [shopizer-ecommerce/shopizer#119]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'categoryDao': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.shopizer.modules.shipping.distance.ShippingDistancePreProcessorImpl] for bean with name 'shippingDistancePreProcessor' defined in class path resource [spring/processors/shopizer-core-shipping-processors.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: 

com/salesmanager/core/modules/integration/shipping/model/ShippingQuotePrePostProcessModule
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.shopizer.modules.shipping.distance.ShippingDistancePreProcessorImpl] for bean with name 'shippingDistancePreProcessor' defined in class path resource [spring/processors/shopizer-core-shipping-processors.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/salesmanager/core/modules/integration/shipping/model/ShippingQuotePrePostProcessModule

**Comment by thisara99** [comment]
https://github.com/shopizer-ecommerce/shopizer/issues/65

Seems like you have to clone instead of downloading the zip.

**Comment by shopizer-ecommerce** [comment]
This was an old issue with earlier 2.0.3 commits. Not an issue with 2.04
