### ISSUE TITLE
Update Parent Pom.xml to handle Dependencies

### ISSUE THREAD

**Issue by KrishnaPhani** [shopizer-ecommerce/shopizer#120]
Currently, each of the child projects have their poms with all of the dependencies with their versions listed out and this causes version update on libraries to be updated on each of the poms in the child projects. 

In order to resolve this, I would suggest we should declare dependency management in the parent pom and let the child pom's inherit these dependencies. This would remove unnecessary version mismatch issues like say child one uses v1 of library and another child would be using v2 of the same library and this "may" potentially create an issue at run time.

**Comment by shopizer-ecommerce** [comment]
Will be the case in 2.0.5
