### ISSUE TITLE
Misspelled "recaptcha" term in the file ApplicationConstants

### ISSUE THREAD

**Issue by developer10** [shopizer-ecommerce/shopizer#123]
D:\xxxx\shopizer-master\sm-shop\src\main\java\com\salesmanager\web\constants\ApplicationConstants.java

	public final static String RECAPTCHA_URL = "shopizer.recapatcha_url";
	public final static String RECAPTCHA_PRIVATE_KEY = "shopizer.recapatcha_private_key";
	public final static String RECAPTCHA_PUBLIC_KEY = "shopizer.recapatcha_public_key";

**_recapatcha_** should spell: **_recaptcha_**

**Comment by shopizer-ecommerce** [comment]
Fixed in 2.0.5
