### ISSUE TITLE
how to solve the dependency of shopizer when you set it up on eclipse neon on with jdk1.8

### ISSUE THREAD

**Issue by albertjone** [shopizer-ecommerce/shopizer#124]
I have download the shopizer2.0.5, and use eclipse neon to import the project, but it show a lot of errors, and most of them are losses of dependencies. I tried to add some external jar files which I downloaded from websites into the build path. However, the loss of dependencies is too big and some of the jar packages can’t be found in my searching. I doubt whether my solution is wrong or not. So, any guy could just solve this problem.

**Comment by albertjone** [comment]
i would like to send some photos of my issue, but github doesn't provide the any way to upload pictures.

**Comment by shopizer-ecommerce** [comment]
You should use 2.0.4, we are not done yet with 2.0.5, still runtime issues from the migration of Spring 4

**Comment by umeshawasthi** [comment]
closing this ticket since 2.0.5 is under development and not ready.

**Comment by mosiac-io** [comment]
@shopizer-ecommerce 
Is 2.0.5 officially out now?
