### ISSUE TITLE
Problems running the tests on sm-core running on java 8

### ISSUE THREAD

**Issue by ruilorenzetti** [shopizer-ecommerce/shopizer#126]
I did the migration of the software to Java 8, this is quite simple , and now it is running on java 8 / tomcat 8.5, (The shop and admin running like a charm).

The problem is about the unit tests.
Most of the errors is because the tests can not commit your changes on the database.
These tests running before commiting your changes   @shopizer-ecommerce , @umeshawasthi,  @k1park, @dimitrove ? Someone else knows about this question ?   

Thanks in advanced
Rui Carlos Lorenzetti

**Comment by ruilorenzetti** [comment]
In 2.0.4 @umeshawasthi, the system goes up already without any  problem.  My question is about the tests running before ?  Just because the unit tests are, by definition,  rollback-only and 42 tests are broken because of this.(rollback-only)  on sm-core.

**Comment by shopizer-ecommerce** [comment]
2.0.4 needs to be ran with java 7. We are planning to release 2.0.5 soon that will support java 8
