### ISSUE TITLE
com.shopizer.search.services.worker.objectIndexerImpl  Faild to load 

### ISSUE THREAD

**Issue by kspengjun** [shopizer-ecommerce/shopizer#129]
Error:  com.shopizer.search.services.worker.objectIndexerImpl  Faild to load 
What's the wrong ?  How can i do it ?

I use the  Shopizer 2.4, elastsearch 2.4,Jdk1.7 Tomcat8.0

**Comment by shopizer-ecommerce** [comment]
Need to have elastic search running before starting the application :-)

http://shopizer-ecommerce.github.io/shopizer/#search
