### ISSUE TITLE
Unable to install ($mvn clean install)  2.0.4 because long directory path

### ISSUE THREAD

**Issue by metalbreeze** [shopizer-ecommerce/shopizer#130]
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.shopizer:sm-core-model:jar:2.0.3-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be u
nique but found duplicate declaration of plugin org.bsc.maven:maven-processor-pl
ugin @ com.shopizer:sm-core-model:[unknown-version], C:\workspace\codeBase\gitRe
pository\shopping\shopizer\sm-core-model\pom.xml, line 425, column 13
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] shopizer
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-core
[INFO] sm-shop
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building shopizer 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ shopizer ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ shopizer ---
[INFO] Installing c:\workspace\codeBase\gitRepository\shopping\shopizer\pom.xml
to c:\Progwvd\IDE\MavenRepository\com\shopizer\shopizer\2.0.3-SNAPSHOT\shopizer-
2.0.3-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-model 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.asp
ectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org
.aspectj:aspectjweaver:jar:1.5.4
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core-model ---
[INFO] Deleting C:\workspace\codeBase\gitRepository\shopping\shopizer\sm-core-mo
del\target
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] shopizer ........................................... SUCCESS [  0.532 s]
[INFO] sm-core-model ...................................... FAILURE [  2.124 s]
[INFO] sm-core-modules .................................... SKIPPED
[INFO] sm-core ............................................ SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.925 s
[INFO] Finished at: 2017-01-28T02:21:39+08:00
[INFO] Final Memory: 9M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:c
lean (default-clean) on project sm-core-model: Failed to clean project: Failed t
o delete C:\workspace\codeBase\gitRepository\shopping\shopizer\sm-core-model\tar
get -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :sm-core-model
[log.txt](https://github.com/shopizer-ecommerce/shopizer/files/736011/log.txt)

**Comment by umeshawasthi** [comment]
My recommendation is to try 2.0.4

**Comment by metalbreeze** [comment]
It is 2.0.4
2281220shopizer>ll .git/refs/heads
total 1
-rw-rw-r--+ 1 niesh Domain Users 41 Jan 26 03:52 2.0.4
0281220shopizer>git rev-parse HEAD
fe8d6bcd8491375e47a7e963b89cf092299ac4f3
0281220shopizer>git log -1
commit fe8d6bcd8491375e47a7e963b89cf092299ac4f3
Author: Samson <c.samson@cgi.com>
Date:   Tue Dec 20 13:04:50 2016 -0500

    Fixed demo not loading at startup

**Comment by metalbreeze** [comment]
This because "Can not delete" and  this is too long path
After move it to c:\.
the problem gone.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:c
lean (default-clean) on project sm-core-model: Failed to clean project: Failed t
o delete C:\workspace\codeBase\gitRepository\shopping\shopizer\sm-core-model\tar
get -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project
sm-core-model: Failed to clean project: Failed to delete C:\workspace\codeBase\g
itRepository\shopping\shopizer\sm-core-model\target
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor

**Comment by shopizer-ecommerce** [comment]
That one could not be reproduced under 2.0.5
