### ISSUE TITLE
Exporting Configuration and Content

### ISSUE THREAD

**Issue by sdebrosse** [shopizer-ecommerce/shopizer#131]
What's the best way to export configuration settings (payment methods, theme, social media details, etc.), content (pictures, main banner, catalog information) and then import both into a new instance of shopizer?

I'm looking for a solution that can be run in an automated way.

**Comment by shopizer-ecommerce** [comment]
What we do now is very simple

Export database content and import in a new schema
Copy either physical Apcache root web site configured for shopizer
or copy infinispan files 

files
     repos
     store

Infinispan path is configured in infinispan_configuration.xml
