### ISSUE TITLE
The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by omtodkar** [shopizer-ecommerce/shopizer#135]
I am new with spring, I was trying to run this project, I tried in JetBrains and recently in STS, I am facing this issue.

Build Log
---
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.shopizer:sm-core-model:jar:2.0.3-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/pom.xml, line 426, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] shopizer
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-core
[INFO] sm-shop
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building shopizer 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ shopizer ---
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/pom.xml to /Users/Omkar/.m2/repository/com/shopizer/shopizer/2.0.3-SNAPSHOT/shopizer-2.0.3-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-model 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] 
[INFO] --- maven-processor-plugin:3.2.0:process (process) @ sm-core-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 4.3.0.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source '1.8'
[INFO] 
[INFO] --- maven-processor-plugin:3.2.0:process (default) @ sm-core-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 4.3.0.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source '1.8'
[INFO] 
[INFO] --- apt-maven-plugin:1.1.3:process (default) @ sm-core-model ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ sm-core-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 299 source files to /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ sm-core-model ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-model ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core-model ---
[INFO] Building jar: /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/target/sm-core-model-2.0.3-SNAPSHOT.jar
[INFO] META-INF/maven/com.shopizer/sm-core-model/pom.xml already added, skipping
[INFO] META-INF/maven/com.shopizer/sm-core-model/pom.properties already added, skipping
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-model ---
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/target/sm-core-model-2.0.3-SNAPSHOT.jar to /Users/Omkar/.m2/repository/com/shopizer/sm-core-model/2.0.3-SNAPSHOT/sm-core-model-2.0.3-SNAPSHOT.jar
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core-model/pom.xml to /Users/Omkar/.m2/repository/com/shopizer/sm-core-model/2.0.3-SNAPSHOT/sm-core-model-2.0.3-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-modules 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ sm-core-modules ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core-modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ sm-core-modules ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-modules ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core-modules ---
[INFO] Building jar: /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/target/sm-core-modules-2.0.3-SNAPSHOT.jar
[INFO] META-INF/maven/com.shopizer/sm-core-modules/pom.xml already added, skipping
[INFO] META-INF/maven/com.shopizer/sm-core-modules/pom.properties already added, skipping
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-modules ---
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/target/sm-core-modules-2.0.3-SNAPSHOT.jar to /Users/Omkar/.m2/repository/com/shopizer/sm-core-modules/2.0.3-SNAPSHOT/sm-core-modules-2.0.3-SNAPSHOT.jar
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core-modules/pom.xml to /Users/Omkar/.m2/repository/com/shopizer/sm-core-modules/2.0.3-SNAPSHOT/sm-core-modules-2.0.3-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 45 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ sm-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 282 source files to /Users/Omkar/Workspace/Spring/shopizer/sm-core/target/classes
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/main/java/com/salesmanager/core/modules/order/ODSInvoiceModule.java: /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/main/java/com/salesmanager/core/modules/order/ODSInvoiceModule.java uses or overrides a deprecated API.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/main/java/com/salesmanager/core/modules/order/ODSInvoiceModule.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/main/java/com/salesmanager/core/modules/integration/payment/impl/StripePayment.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/main/java/com/salesmanager/core/modules/integration/payment/impl/StripePayment.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ sm-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to /Users/Omkar/Workspace/Spring/shopizer/sm-core/target/test-classes
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/test/java/com/salesmanager/test/utils/ExportSchema.java: Some input files use or override a deprecated API.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/test/java/com/salesmanager/test/utils/ExportSchema.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/test/java/com/salesmanager/test/isolated/IsolatedTestCase.java: /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/test/java/com/salesmanager/test/isolated/IsolatedTestCase.java uses unchecked or unsafe operations.
[INFO] /Users/Omkar/Workspace/Spring/shopizer/sm-core/src/test/java/com/salesmanager/test/isolated/IsolatedTestCase.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core ---
[INFO] Building jar: /Users/Omkar/Workspace/Spring/shopizer/sm-core/target/sm-core-2.0.3-SNAPSHOT.jar
[INFO] META-INF/maven/com.shopizer/sm-core/pom.xml already added, skipping
[INFO] META-INF/maven/com.shopizer/sm-core/pom.properties already added, skipping
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core ---
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core/target/sm-core-2.0.3-SNAPSHOT.jar to /Users/Omkar/.m2/repository/com/shopizer/sm-core/2.0.3-SNAPSHOT/sm-core-2.0.3-SNAPSHOT.jar
[INFO] Installing /Users/Omkar/Workspace/Spring/shopizer/sm-core/pom.xml to /Users/Omkar/.m2/repository/com/shopizer/sm-core/2.0.3-SNAPSHOT/sm-core-2.0.3-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-shop 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- aspectj-maven-plugin:1.2:compile (default) @ sm-shop ---
[ERROR] The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] shopizer ........................................... SUCCESS [  0.375 s]
[INFO] sm-core-model ...................................... SUCCESS [  9.388 s]
[INFO] sm-core-modules .................................... SUCCESS [  0.227 s]
[INFO] sm-core ............................................ SUCCESS [  4.848 s]
[INFO] sm-shop ............................................ FAILURE [  2.741 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.771 s
[INFO] Finished at: 2017-02-15T01:08:41+05:30
[INFO] Final Memory: 56M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.2:compile (default) on project sm-shop: Compiler errors :
[ERROR] error at @RequestMapping(Constants.SHOP_URI)
[ERROR] ^^^^^^^^^^^^^^^^^
[ERROR] /Users/Omkar/Workspace/Spring/shopizer/sm-shop/src/main/java/com/salesmanager/web/shop/controller/order/ShoppingOrderPaymentController.java:61:0::0 The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sm-shop

**Comment by umeshawasthi** [comment]
Can you try with 2.0.4 ? There are some known issue in 2.0.3 and those were fixed in 2.0.4

**Comment by omtodkar** [comment]
I tried on **2.0.4** and **master** branches, I am facing same issue in both.

Which is 2.0.4? As I can see [2.0.3](https://github.com/shopizer-ecommerce/shopizer/blob/2.0.3/pom.xml), [2.0.4](https://github.com/shopizer-ecommerce/shopizer/blob/2.0.4/pom.xml) and [master](https://github.com/shopizer-ecommerce/shopizer/blob/master/pom.xml) has same project version in pom file.

**Comment by yasin3061** [comment]
@omtodkar, are you using Java 1.8 by any chance? I was able to reproduce the same error when I modified eclipse to use jdk 8 instead of jdk 7. Once I changed the configurations to use jdk 7, I was able to compile the project successfully. Let me know if this works.

**Comment by shopizer-ecommerce** [comment]
Use JDK 1.7 up to shopizer 2.0.4
Used JDK 1.8 stating at Shopizer 2.0.5
