### ISSUE TITLE
Zone code can't be unique

### ISSUE THREAD

**Issue by ndhilliprasad** [shopizer-ecommerce/shopizer#142]
Currently ZONE.ZONE_CODE column is unique. It is very much possible that the  zone code be same from different countries. 

For example : Zone code "AP"
Andhra Pradesh - India
Armed Forces Pacific - USA.

After looking at the code I fee it better to remove the unique constraint on the zone_code. please let me how to proceed.

**Comment by ndhilliprasad** [comment]
@umeshawasthi , @shopizer-ecommerce , Could some one through some light on this.

Thanks

**Comment by shopizer-ecommerce** [comment]
Ok i see, 
edit com.salesmanager.core.model.reference.zone.Zone

Remove unique=true
Drop your existing schema (if possible otherwise see MySQL to remove unique)
Rebuild & deploy

	@Column(name = "ZONE_CODE", unique=true, nullable = false)
	private String code;

We will build the constraint on country.code + zone.code

**Comment by ndhilliprasad** [comment]
make sense. I will raise the pull request for this in upcoming days
