### ISSUE TITLE
Invalid characters when coming in with a french brower using french language

### ISSUE THREAD

**Issue by shopizer-ecommerce** [shopizer-ecommerce/shopizer#15]
Shop and admin pages display invalid characters when coming in with a french browser

**Comment by k1park** [comment]
add web.xml encodig filter for UTF-8

...
      <filter>
        <filter-name>encodingFilter</filter-name>
        <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
        <init-param>
            <param-name>encoding</param-name>
            <param-value>utf-8</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>encodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
  ...

**Comment by shopizer-ecommerce** [comment]
Solved in sehopizer 2.0.3
