### ISSUE TITLE
Compile question

### ISSUE THREAD

**Issue by tootoohu** [shopizer-ecommerce/shopizer#152]
Hi, I imported this project into my eclipse. and run the maven build. It's successful. But the java file still have compile error. So many red icons in each files.
My configuration is :  Eclipse Mars.2 Release (4.5.2), maven: 3.3.9; m2e plugin: 1.6.2.
Can somebody help? Thank you so much in advance.

**Comment by tootoohu** [comment]
Resolved now.

**Comment by serdarekcx** [comment]
Hello there,
I want to use shopizer on my e-commerche project but i don't know which
version is stable.
Can anybody help me ?
Best regards.

2017-05-25 4:42 GMT+03:00 tootoohu <notifications@github.com>:

**Comment by umeshawasthi** [comment]
Go with 2.0.5, it's the latest and stable build
