### ISSUE TITLE
Shopizer 2.0.5 Admin Login redirect error

### ISSUE THREAD

**Issue by vioao** [shopizer-ecommerce/shopizer#160]
When i config the server context path. The admin login redirect action was wrong.
like this:

---

#### application.properties
`
server.contextPath=/shop
`

---

login the admin

then it redirect to `http:localhost:8080/shop/shop/admin`
but true address is 'http:localhost:8080/shop/admin'

I think the problem is in the `UserAuthenticationSuccessHandler .java`

`
  //response.sendRedirect(request.getContextPath() + "/admin/home.html");
redirectStrategy.sendRedirect(request, response, request.getContextPath() + "/admin/home.html");
`

`request.getContextPath()` should not be added.

**Comment by shopizer-ecommerce** [comment]
Thanks we will look at it

**Comment by shopizer-ecommerce** [comment]
Fixed in version 2.2.0
