### ISSUE TITLE
NullPointerException while placing an order

### ISSUE THREAD

**Issue by loamDeLest** [shopizer-ecommerce/shopizer#172]
Any idea on this ?
  
com.salesmanager.core.business.exception.ServiceException:  java.lang.NullPointerException 	at  com.salesmanager.core.business.services.order.OrderServiceImpl.caculateOrderTotal(OrderServiceImpl.java:368) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at  org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) 	at  org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) 	at  org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) 	at  org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) 	at  org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) 	at  org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) 	at com.sun.proxy.$Proxy214.caculateOrderTotal(Unknown Source) 	at  com.salesmanager.shop.store.controller.order.facade.OrderFacadeImpl.calculateOrderTotal(OrderFacadeImpl.java:188) 	at  com.salesmanager.shop.store.controller.order.facade.OrderFacadeImpl.calculateOrderTotal(OrderFacadeImpl.java:144) 	at  com.salesmanager.shop.store.controller.order.ShoppingOrderController.displayCheckout(ShoppingOrderController.java:389) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at  org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) 	at  org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) 	at  org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) 	at  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832) 	at  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) 	at  org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) 	at  org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) 	at  org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) 	at  org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) 	at  org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 	at  org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:69) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:162) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:68) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) 	at  org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:184) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) 	at  org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:162) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) 	at  org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 	at  org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) 	at  org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) 	at  org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) 	at  org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) 	at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) 	at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) 	at  org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) 	at  org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 	at  org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) 	at  org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) 	at  org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 	at  org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 	at  org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) 	at  org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) 	at  org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) 	at  org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) 	at  org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) 	at  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 	at  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 	at  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException 	at  com.salesmanager.core.business.services.tax.TaxRateServiceImpl.listByCountryZoneAndTaxClass(TaxRateServiceImpl.java:53) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at  org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) 	at  org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) 	at  org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) 	at  org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) 	at  org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) 	at  org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) 	at  org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) 	at com.sun.proxy.$Proxy216.listByCountryZoneAndTaxClass(Unknown Source) 	at  com.salesmanager.core.business.services.tax.TaxServiceImpl.calculateTax(TaxServiceImpl.java:229) 	at  com.salesmanager.core.business.services.order.OrderServiceImpl.caculateOrder(OrderServiceImpl.java:313) 	at  com.salesmanager.core.business.services.order.OrderServiceImpl.caculateOrderTotal(OrderServiceImpl.java:366) 	... 161 more

**Comment by loamDeLest** [comment]
I'm using 2.0.5

**Comment by owenludong** [comment]
It's a bug , you should sign in

**Comment by shopizer-ecommerce** [comment]
Can you debug to see what object is null ?

Signing in should is not required to go through order total calculation, it may have to do with a bad configuration but the stack trace does not say that much

**Comment by loamDeLest** [comment]
Hi,
I did debug and it seems that in the "TaxServiceImpl" class, the "zone" value is never allocated: The different conditions (if {....} else if {...} etc ) are never verified.
The exception occurs at the line:

taxRates = taxRateService.listByCountryZoneAndTaxClass(country, zone, taxClasses.get(taxClassId), store, language);

I replaced this line by the previous one in a previous condition (Just for test):
taxRates = taxRateService.listByCountryStateProvinceAndTaxClass(country, stateProvince, taxClasses.get(taxClassId), store, language);

And the program pass through without throwing the NullPointerException

-----------------------

I was suprised that none of the condition was satisfied: E.g:

if(taxBasisCalculation.name().equals(TaxBasisCalculation.SHIPPINGADDRESS)){
.....

I changed it to:
if(taxBasisCalculation.name().equals(TaxBasisCalculation.SHIPPINGADDRESS.toString())){
...
and the condition was satisfied...

But ther should be something else bad, because the even with that the "taxRates = taxRateService.listByCountryZoneAndTaxClas....." continues to thow exception...


Your help will be appreciate.

**Comment by rakesh1191** [comment]
Same Problem...Please Provide the solution!!!

**Comment by Emma04** [comment]
I am facing the same problem! 
Any help plz =)

**Comment by rakesh1191** [comment]
You need to configure shipping module. Go into an admin panel and set it up first.
@shopizer-ecommerce Shopizer needs proper documentation.

**Comment by Emma04** [comment]
@rakesh1191 thank for your suggestion but shipping module for my case is configured but still same error!

**Comment by rakesh1191** [comment]
First try only with weight based shipping, disable others and while doing configuration for it do not forget to set a region (according to the store region) which is at the bottom of the page.

**Comment by Emma04** [comment]
Thank you for your support. I am still facing this error even if I changed the store location to Canada (as default) and disable other option and configure just weight based shipping... I still have this page error when I confirm the order (payment). Any suggestion?

**Comment by shopizer-ecommerce** [comment]
This is fixed in upcoming version

In the meantime

open com.salesmanager.core.business.services.tax.TaxServiceImpl

At line 167

insert

		if(zone == null && StringUtils.isBlank(stateProvince)) {
			return null;
		}

**Comment by Emma04** [comment]
Thank you I will try it and will give you my feedback

A small notice I don't know if it is useful or not. I download shopizer again and I didn't face this issue. I was able to purchase with no pointer null however when connect with mysql I faced this issue.

**Comment by shopizer-ecommerce** [comment]
Fixed in version 2.2.0
