### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by wisien92** [shopizer-ecommerce/shopizer#178]
I have a question regarding GPLv3 license.

According to:
https://choosealicense.com/licenses/

When I want to distribute software I need to make the modifications public. But when I modify the software (here - shopizer) and use it commercially as a shop I am not distributing the software just a service that this software enables - am I right? 

I am not sure if this is correct place to ask so sorry for inconvenience.

**Comment by shopizer-ecommerce** [comment]
You can do whatever you want with LGPL v3 and shopizer

**Comment by shopizer-ecommerce** [comment]
Will close this
