### ISSUE TITLE
how to package to jar?

### ISSUE THREAD

**Issue by wangay** [shopizer-ecommerce/shopizer#185]
what's the right config in pom.xml?

**Comment by shopizer-ecommerce** [comment]
Change from

	<artifactId>sm-shop</artifactId>
	<packaging>war</packaging>

to

	<artifactId>sm-shop</artifactId>
	<packaging>jar</packaging>

in sm-shop/pom.xml

**Comment by wangay** [comment]
no needing this???

<build>
        <plugins>


            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                
                <configuration>
                    <mainClass>com.salesmanager.shop.application.ShopApplication</mainClass>
                    
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>

        
        <resources>
            <resource>
                <directory>src/main/webapp</directory>
                <targetPath>META-INF/resources</targetPath>
                <includes>
                    <include>**/**</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/**</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>

**Comment by wangay** [comment]
when I add those above and run it . it said :
```
java.io.FileNotFoundException: class path resource [templates/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/wangany/Documents/git/shopizer/sm-shop/target/sm-shop-2.0.5-SNAPSHOT.jar!/lib/sm-core-2.0.5-SNAPSHOT.jar!/templates/
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
```
