### ISSUE TITLE
error  first run from Eclipse  (drools issue)

### ISSUE THREAD

**Issue by cuzur** [shopizer-ecommerce/shopizer#189]
maven clean  ok, maven create source ok, maven install ok.
when i run application i have one error 
in  sm-core\src\\main\resource\spring\shopizer-core-rules.xml
for line     \
    <drools:kbase id="shippingMethodDecisionBase">
        <drools:resources>
            <drools:resource type="DTABLE" source="classpath:rules/shipping-decision-rules.xls"/>
        </drools:resources>
    </drools:kbase>
error is :
"Multiple annotations found at this line:
	- schema_reference.4: Failed to read schema document 'http://drools.org/schema/drools-spring.xsd', because 1) could not find the document; 2) the 
	 document could not be read; 3) the root element of the document is not <xsd:schema>.
	- cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'drools:kbase'."  
i need help

**Comment by shopizer-ecommerce** [comment]
This is a xml validation with eclipse, you can ommit xml validation on this file
