### ISSUE TITLE
where i can find database structure?

### ISSUE THREAD

**Issue by nguyenthedan** [shopizer-ecommerce/shopizer#202]
I want to see struct of database but i can't know find where? Anyone can see me. Thanks.

**Comment by silvioincalza** [comment]
Hi, the struct of database is created or updated by hibernate via hbm2ddl.
You can found some reference on https://github.com/shopizer-ecommerce/shopizer/wiki/Shopizer-configuration.

**Comment by shopizer-ecommerce** [comment]
configure shopizer with mysql
run shopizer
install mysql workbench (free tool)
connect to database
reverse engineer schema for visual structure
