### ISSUE TITLE
Shopizer 2.0.3 build failed with jdk 1.8

### ISSUE THREAD

**Issue by radrao24** [shopizer-ecommerce/shopizer#212]
Hi,

We have an year old website developed using shopizer 2.0.3. We need to do few customizations so trying to set it up locally on a Mac OS.

Build fails while compiling sm-core and hence the rest is skipped. 
sm-core Q-Classes are not loaded.

We tried with mvn generate-sources before install but it did not help.

followed these steps inside shopizer folder.

mvn clean
mvn generate-sources
mvn install [install fails]

jdk version is 1.8. will that cause any issues? pasted error below.

Appreciate your help.

[INFO] Reactor Summary:
[INFO] 
[INFO] shopizer 2.0.3-SNAPSHOT ............................ SUCCESS [  0.243 s]
[INFO] sm-core-model ...................................... SUCCESS [  2.995 s]
[INFO] sm-core-modules .................................... SUCCESS [  0.187 s]
[INFO] sm-core ............................................ FAILURE [  2.038 s]
[INFO] sm-shop 2.0.3-SNAPSHOT ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.599 s
[INFO] Finished at: 2018-04-03T15:30:41-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project sm-core: Compilation failure: Compilation failure: 
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/user/dao/UserDaoImpl.java:[11,49] cannot find symbol
[ERROR]   symbol:   class QGroup
[ERROR]   location: package com.salesmanager.core.business.user.model
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/user/dao/UserDaoImpl.java:[12,49] cannot find symbol
[ERROR]   symbol:   class QUser
[ERROR]   location: package com.salesmanager.core.business.user.model
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/catalog/product/dao/attribute/ProductAttributeDaoImpl.java:[10,60] cannot find symbol
[ERROR]   symbol:   class QProduct
[ERROR]   location: package com.salesmanager.core.business.catalog.product.model
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/catalog/product/dao/attribute/ProductAttributeDaoImpl.java:[12,70] cannot find symbol
[ERROR]   symbol:   class QProductAttribute
[ERROR]   location: package com.salesmanager.core.business.catalog.product.model.attribute
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/catalog/product/dao/attribute/ProductAttributeDaoImpl.java:[13,70] cannot find symbol
[ERROR]   symbol:   class QProductOption
[ERROR]   location: package com.salesmanager.core.business.catalog.product.model.attribute
[ERROR] /Users/radhikarao/gitClones/QSC/Development/shopizer-2.0.3/sm-core/src/main/java/com/salesmanager/core/business/catalog/product/dao/attribute/ProductAttributeDaoImpl.java:[14,70] cannot find symbol

**Comment by shopizer-ecommerce** [comment]
version 2.0.3 requires java 7
