### ISSUE TITLE
Question: sm-core as a maven artifact

### ISSUE THREAD

**Issue by BryantDavidDavis** [shopizer-ecommerce/shopizer#213]
Hi, I apologize if this isn't a useful question, but I think this project is great, and I was wondering if there is a reason that the 'sm-core' module isn't published as a maven artifact?  I see that sm-core-model, sm-core-modules, etc. are, but  it would seem useful to have sm-core itself as an artifact?

**Comment by umeshawasthi** [comment]
@BryantDavidDavis sm-core is also Maven artifact, it will be deployed in your local maven repo (check .m2 folder), This is not on the central repo since sm-core carry the core logic and subjected to customization based on the requirement.
