### ISSUE TITLE
No configs.property file !

### ISSUE THREAD

**Issue by Harikumar200** [shopizer-ecommerce/shopizer#225]
Just clarification needed !

for CMS configuration, this what a document says..

> "The default CMS implementation uses JBoss Infinispan that will store files on disk. To change Infinispan cache location
> 
> Edit shopizer\sm-core\src\main\resources\configs.properties
> 
> # Infinispan Configuration
> infinispan.cache.location=./infinispan"

But I didn't find any such file ! Do I need to create it ?

**Comment by shopizer-ecommerce** [comment]
shopizer-core.properties

#Infinispan configuration
config.cms.store.location=./files/store
config.cms.files.location=./files/repos
