### ISSUE TITLE
Failed to execute goal on project sm-shop

### ISSUE THREAD

**Issue by mahanandajreddy** [shopizer-ecommerce/shopizer#238]
While Maven build im getting this error please help me solve this issue:

[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.shopizer:sm-shop:war:2
.2.0-SNAPSHOT: Failed to collect dependencies at org.springframework.social:spring-social-facebook:jar:3.0.0.M3: Failed
to read artifact descriptor for org.springframework.social:spring-social-facebook:jar:3.0.0.M3: Could not transfer artif
act org.springframework.social:spring-social-facebook:pom:3.0.0.M3 from/to spring-releases (https://repo.spring.io/libs-
release): peer not authenticated -> [Help 1]
[ERROR]

**Comment by shopizer-ecommerce** [comment]
Maven pull issue
