### ISSUE TITLE
unable to launch shopizer application from browser

### ISSUE THREAD

**Issue by Venkateswarlu-Hexaware** [shopizer-ecommerce/shopizer#254]
- I use Eclipse, Windows, h2 database and 2.2.0 branch code to launch the application. 
-  started the application like start as java application
**changes in file:**
changed packaging war to jar in sm-shop/pom.xml
database properties changed to hibernate.hbm2ddl.auto=create-drop
**ISSUE**
hit the application through the browser and showing error on web page.

=============Error=============
This localhost page can’t be found
No webpage was found for the web address: http://localhost:8080/shop
Search Google for localhost 8080 shop
HTTP ERROR 404

===================================
Note: No error is showing on the eclipse console.
please help me to resolve this issue.

**Comment by shopizer-ecommerce** [comment]
Now it still only supports war file
