### ISSUE TITLE
Unable to fins the customer register or login link in footer of a shop

### ISSUE THREAD

**Issue by siddupatil** [shopizer-ecommerce/shopizer#27]
Unable to fins the customer register or login link in footer of a shop , it is expecting some permission, hasRole(AUTHCUSTOMER) am i need to any access related configuration for this. i am new to this please help me out of this

**Comment by umeshawasthi** [comment]
We need more details before we can help?
How you deployed your application? which Shopizer branch you are working currently?

**Comment by syamsathyan** [comment]
Run the shop module with basic default properties.
The login link is simply missing, is this a confirmed bug / an missing property?

**Comment by shopizer-ecommerce** [comment]
in the admin settings enable 'customer serction' from the configuration page

THat will show up the account login box and once logged in you will be able to see that link

**Comment by syamsathyan** [comment]
Thanks
