### ISSUE TITLE
I clone the project and try to building it, it's failed: not found ProductType.code

### ISSUE THREAD

**Issue by monkeyk** [shopizer-ecommerce/shopizer#28]
I clone the project and try to building it, it's failed: not found ProductType.code

in master and 2.0.1 branches

**Comment by shopizer-ecommerce** [comment]
Please for now use 2.0.0 branch, 2.0.1 has been reported unstable and should be fixed in the next few days

**Comment by monkeyk** [comment]
Hi, V-2.0.0 have the same issues

**Comment by monkeyk** [comment]
I am interesting the project; Can i help do something for it

**Comment by shopizer-ecommerce** [comment]
Sure leave us an email for personal email support@shopizer.com

**Comment by shopizer-ecommerce** [comment]
Branch 2.0.1 as 2.0.0 mvnclean mvn generate-sources and mvn install
