### ISSUE TITLE
[enhancement] Is it possible to introduce lombok framework ?

### ISSUE THREAD

**Issue by DzmitryNev** [shopizer-ecommerce/shopizer#280]
Guys, I think we can use project lombook to reduce the amount of code. Compatible version of lombook already included into spring boot.
https://projectlombok.org

I also propose to use limit of lombook annotations:
```
@Data
@Slf4j
@Getter/@Setter
@AllArgsConstructor
@NoArgsConstructor
```

how to include it into pom.xml :

```
<dependencies>
                        <dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
		</dependency>
</dependencies>
```
@shopizer-ecommerce @umeshawasthi

**Comment by rahilsh** [comment]
Must needed nowadays

**Comment by umeshawasthi** [comment]
@DzmitryNev Agree, help is more than welcome :)

**Comment by shopizer-ecommerce** [comment]
Agreed !! Please send us any usage recommendation

**Comment by DzmitryNev** [comment]
Please review my PR: https://github.com/shopizer-ecommerce/shopizer/pull/281/files
This PR includes:
1) introduction lombook
Refactoring
2) @Controller -> @Restcontroller
3) @RequiestMapping -> @GetMapping/ @PostMapping / @PutMapping 
4) Introduce GenericRuntimeException/RestApiException/ServiceRuntimeException/ResourceNotFoundException
4) Introduce controller advices for ResourceNotFoundException(http 404) and RestApiException(http 503) - i think it is better way to handle it.
5) Introduced ErrorEntity  with errorCode and message(example of usage lombook).

Also please see the example of usage lomobook: https://www.baeldung.com/intro-to-project-lombok

**Comment by shopizer-ecommerce** [comment]
Hi, thanks for the PT, looking into this. Got lots of questions and also possibility in the integration with Kotlin (which seems to be a new hype), let me know if there are similarity with what you are trying to achieve - write less code

**Comment by DzmitryNev** [comment]
@shopizer-ecommerce 
Please do not hestitate to write any questions and comment PR.
My PR consists of 2 parts: 
1 lombook integration(changes pom.xml)
2 refactoring:
  a) removed old annotation and adding new Spring annotation(@RequestController/ @GetMapping)
  b) trying to avoid checked exception and wrapping it to RuntimeException - because almost all handling the same ( GenericRuntimeException / ResourceNotFoundException  / ServiceRuntimeException / RestApiException )
  c) adding @ControllerAdvice to handle errors (see b.)

Regards the second part of PR:
I think this changes do not depends on language. It is refactoring on the level of framework usage.
I think it would be better to throw RuntimeException into one place(service or facade) and handle it into one place(controller advice or controller if needs). 
In the old approach there is throwing CheckException into one place(for example service) and handle it into many places(catch and wrap and handle it into controller at the end).
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

**Comment by DzmitryNev** [comment]
@shopizer-ecommerce
Created new PR contains only lombook changes
https://github.com/shopizer-ecommerce/shopizer/pull/285/files
