### ISSUE TITLE
[enhancement] code quality tool intro

### ISSUE THREAD

**Issue by DzmitryNev** [shopizer-ecommerce/shopizer#286]
Maybe it would be better to enable any quality tool(example sonarqube) for shopizer.
As far as I know sonarcloud 'Free for Open-Source Projects'
See more https://sonarcloud.io.

Also i just try to run sonarqube for my fork of shopizer manually:
see the results: https://sonarcloud.io/dashboard?id=DzmitryNev_shopizer

@shopizer-ecommerce
@umeshawasthi

**Comment by shopizer-ecommerce** [comment]
Hi, yes it is now in process ! quality tools are on the way on our test environment

**Comment by shopizer-ecommerce** [comment]
Dmitry, interested in giving uys a hand with this :-) ?

**Comment by earmitage** [comment]
This is likely the wrong place but I have sent my details on the contact us twice to offer assistance with the development.

**Comment by shopizer-ecommerce** [comment]
Yes, please use this form http://www.shopizer.com/contact.html, i will take care of this ticket

**Comment by shopizer-ecommerce** [comment]
Hi, ok, thanks for the notice, will check contact form
use carl@shopizer.com
    On Wednesday, January 9, 2019, 10:38:33 a.m. EST, Evans Armitage <notifications@github.com> wrote:  
 
 
This is likely the wrong place but I have sent my details on the contact us twice to offer assistance with the development.

**Comment by shopizer-ecommerce** [comment]
Contact form seems to have problem, here is the direct contact carl@shopizer.com

**Comment by shopizer-ecommerce** [comment]
on the way
