### ISSUE TITLE
[enhancement] proposal to change *populators* to converters 

### ISSUE THREAD

**Issue by DzmitryNev** [shopizer-ecommerce/shopizer#289]
Maybe it would be better to change *populators*(ex CustomerBillingAddressPopulator - this class only populate DTO) to converters(create and populate DTO), because very frequent case the follwing:
 
```
public void someMethod(){
   Populator populator = new Populator();
   DTO dto = new DTO();
   populator .populate(object,dto);
   // use dto
}
```

I thing it would be better to change the following:
```
@Inject
Converter<Shop, ShopTO> converter;

public void someMethod(){
   ShopTO shopTo = converter.convert(shop);
}
```
Also it can be changed only into related to Rest API endpoints.

@shopizer-ecommerce 
@umeshawasthi

**Comment by umeshawasthi** [comment]
@DzmitryNev : Agree, I like to change it to generic conversion framework
