### ISSUE TITLE
So many java source missing. Can't work ?

### ISSUE THREAD

**Issue by fabricek** [shopizer-ecommerce/shopizer#29]
This is an extract for  mvn generate-sources why so many sources are missing ?
------------
 symbol:   class QCountryDescription
  location: package com.salesmanager.core.business.reference.country.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\reference\cu
rrency\dao\CurrencyDaoImpl.java:11: error: cannot find symbol
import com.salesmanager.core.business.reference.currency.model.QCurrency;
                                                              ^
  symbol:   class QCurrency
  location: package com.salesmanager.core.business.reference.currency.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\reference\zo
ne\dao\ZoneDaoImpl.java:12: error: cannot find symbol
import com.salesmanager.core.business.reference.zone.model.QZone;
                                                          ^
  symbol:   class QZone
  location: package com.salesmanager.core.business.reference.zone.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\reference\zo
ne\dao\ZoneDaoImpl.java:13: error: cannot find symbol
import com.salesmanager.core.business.reference.zone.model.QZoneDescription;
                                                          ^
  symbol:   class QZoneDescription
  location: package com.salesmanager.core.business.reference.zone.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\shoppingcart
\dao\ShoppingCartDaoImpl.java:14: error: cannot find symbol
import com.salesmanager.core.business.shoppingcart.model.QShoppingCart;
                                                        ^
  symbol:   class QShoppingCart
  location: package com.salesmanager.core.business.shoppingcart.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\shoppingcart
\dao\ShoppingCartDaoImpl.java:15: error: cannot find symbol
import com.salesmanager.core.business.shoppingcart.model.QShoppingCartItem;
                                                        ^
  symbol:   class QShoppingCartItem
  location: package com.salesmanager.core.business.shoppingcart.model
[ERROR] diagnostic: C:\Users\Fab\workspace-eclipse\shopizer-master\sm-core\src\main\java\com\salesmanager\core\business\system\dao\M
erchantConfigurationDaoImpl.java:13: error: cannot find symbol
import com.salesmanager.core.business.system.model.QMerchantConfiguration;

**Comment by shopizer-ecommerce** [comment]
Those are generated proxy classes which are sometimes not generated by the build process. In that case run maven genrate-sources on sm-core

Right click on sm-core
- maven clean
- maven generate-sources
- maven install

**Comment by shopizer-ecommerce** [comment]
Q classes are generated stubs, Run maven generate-sources
