### ISSUE TITLE
Compilation while building master branch

### ISSUE THREAD

**Issue by siddu007** [shopizer-ecommerce/shopizer#30]
Latest code having compilations ?
I am not able to build the master branch code (sm-core) because of compilations.In com.salesmanager.core.business.user.dao.UserDaoImpl.java getting compilations i,e not able to resolve imports for 

com.salesmanager.core.business.user.model.QGroup;
com.salesmanager.core.business.user.model.QUser;

Since QUser and QGroup does not exist - Is it really a compilation or I am missing something ? Please help me out 

I am using intellij idea with jdk version jdk1.7.0_67.

Thanks,

**Comment by shopizer-ecommerce** [comment]
Those are generated proxy classes

To solve that, on sm-core run:
- mvn clean
- mvn generate-sources
- mvn install

Q classes are generated in the build path and will now compile from your IDE

**Comment by siddu007** [comment]
Thanks shopizer-ecommerce - It works fine.
