### ISSUE TITLE
Not able to Send Email

### ISSUE THREAD

**Issue by JagdeepDhiman** [shopizer-ecommerce/shopizer#306]
I have to write because I try to send the mail from your contact us option so not able to do that. So sharing my query:-

Want to use it for the client project,
So need clarity about the license because I am looking for an open source and free to use it anywhere without any condition. We can modify the code based on our need without any condition.
If we can do it then I will continue otherwise have to look another option :)
Please reply
-Thanks-

**Comment by carlsamson** [comment]
Licence is Apache 2 - See it here https://github.com/shopizer-ecommerce/shopizer/blob/2.3.0/LICENSE.md

No restrictions, you can use it for your client

**Comment by JagdeepDhiman** [comment]
Thank you
