### ISSUE TITLE
Error while create table UserConnection with mysql 8.x

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#308]
the script "create table UserConnection (providerId varchar(255) not null, providerUserId varchar(255) not null, userId varchar(255) not null, accessToken varchar(255), displayName varchar(255), expireTime bigint, imageUrl varchar(255), profileUrl varchar(255), rank integer not null, refreshToken varchar(255), secret varchar(255), primary key (providerId, providerUserId, userId) " have an error in SQL syntax;
Most likely because Rank is a MySQL reserved keyword (in versions 8+)
Reference: https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R

**Comment by shopizer-ecommerce** [comment]
Will be fixed in upcoming 2.4.0

**Comment by shopizer-ecommerce** [comment]
Fixed in release 2.4.0
