### ISSUE TITLE
connection refused http://localhost:9200

### ISSUE THREAD

**Issue by zellur** [shopizer-ecommerce/shopizer#310]

**Comment by umeshawasthi** [comment]
are you working on the 2.3.0? Can you share more detail?

**Comment by zellur** [comment]
Yes.. i am working on 2.3.0. i get this error when i search for product. And another things is there is no test data.

**Comment by umeshawasthi** [comment]
You need to have elastic search server up and running.default We set port for elastic to 9200.Refer to shopizer-core.properties for more detail

**Comment by zellur** [comment]
@umeshawasthi  please can tell me what i need to do for seeing test data? take a look on my home page
![screenshot from 2019-03-01 14-39-39](https://user-images.githubusercontent.com/11698852/53626437-e5520d00-3c2f-11e9-9ebe-cdbfceff914c.png)

**Comment by shopizer-ecommerce** [comment]
Please ask questions to Shopizer forum, let's keep this place for software bugs and enhancements
