### ISSUE TITLE
Theme exoticamobilia can not add item to cart

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#314]
when use exoticamobilia theme, function add to cart not working, but it does with generic theme.

**Comment by carlsamson** [comment]
In your browser console or in server logs do you see any errors ?

**Comment by hungtrquoc** [comment]
I think it error while load js and css.
![capture](https://user-images.githubusercontent.com/4296584/53930407-bb7f6700-40c3-11e9-8d7f-43aed0c866ac.PNG)

**Comment by shopizer-ecommerce** [comment]
Ok, will rais this as an issue, will provide a quick fix

**Comment by shopizer-ecommerce** [comment]
Fixed in master

See commit here https://github.com/shopizer-ecommerce/shopizer/commit/f4dc5cd82698c759e3529b16e00c360fc8f62f0a
