### ISSUE TITLE
2.4.0 built failed sm-core-model 

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#315]
Building index for all the packages and classes...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\overview-tree.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\index-all.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\deprecated-list.html...
Building index for all classes...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\allclasses-frame.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\allclasses-noframe.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\index.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\overview-summary.html...
Generating $SHOPIZER_HOME\sm-core-model\target\apidocs\help-doc.html...
1 warning
[WARNING] Javadoc Warnings
[WARNING] $SHOPIZER_HOME\sm-core-model\src\main\java\com\salesmanager\core\model\shipping\ShippingConfiguration.java:116: warning: no @param for shipType
[WARNING] public void setShipType(String shipType) {
[WARNING] ^
[INFO] Building jar: $SHOPIZER_HOME\sm-core-model\target\sm-core-model-2.4.0-javadoc.jar
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent-integration (default-prepare-agent-integration) @ sm-core-model ---
[INFO] argLine set to -javaagent:C:\\Users\\user\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=D:\\CaNhan\\DuAnNgoai\\WebsiteEcommerce\\shopizer\\shopizer-2.4.0\\sm-core-model\\target\\jacoco-it.exec
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:report (default-report) @ sm-core-model ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:report-integration (default-report-integration) @ sm-core-model ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:check (default-check) @ sm-core-model ---
[INFO] Skipping JaCoCo execution due to missing execution data file:$SHOPIZER_HOME\sm-core-model\target\jacoco.exec
[INFO]
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ sm-core-model ---
'gpg.exe' is not recognized as an internal or external command,
operable program or batch file.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shopizer 2.4.0:
[INFO]
[INFO] shopizer ........................................... SUCCESS [  1.948 s]
[INFO] sm-core-model ...................................... FAILURE [ 24.706 s]
[INFO] sm-core-modules .................................... SKIPPED
[INFO] sm-core ............................................ SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.248 s
[INFO] Finished at: 2019-03-09T15:13:39+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project sm-core-model: Exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sm-core-model

**Comment by shopizer-ecommerce** [comment]
Fixed in commit
https://github.com/shopizer-ecommerce/shopizer/commit/9e2920ec234d0478b654ad92d8931d9e6e4e2bd7
