### ISSUE TITLE
Re-deploy war file, lose image

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#316]
when re-deploy war file with tomcat, all images not found.
I have to reupload all images.

**Comment by carlsamson** [comment]
As documented here [](http://shopizer-ecommerce.github.io/shopizer/#cms)
default images are saved in application root

To change the location
sm-core/src/main/resources/cms/infinispan_configuration.xml

<property name="location" value="./files/store"/>
change it to a repo where your images are saved, then when deploying that repo won't be overriden

**Comment by shopizer-ecommerce** [comment]
As carl says above
