### ISSUE TITLE
[Urgent] Paypal express checkout redirect wrong url

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#317]
when checkout success, this redirect wrong url:

http://localhost:8080//shop/paypal/checkout.html/success?token=EC-53D28910BF728835J&PayerID=254QNEBX8ZRRS

**Comment by carlsamson** [comment]
Open admin tool

Edit your store
Last field domain name : replace localhost:8080/ with localhost:8080

Have you tried to plug the url in your browser and see if it wors

**Comment by carlsamson** [comment]
Ok, but you said you get this url in the ticket
http://localhost:8080//shop/paypal/checkout.html/success?token=EC-53D28910BF728835J&PayerID=254QNEBX8ZRRS

according to what i see it is a different host, should be http://XX.XX.45.151:8080

- Try it again, then let me know the url generated

- Then take this url, plug it in your browser directly

- What is printed in the console ?

**Comment by shopizer-ecommerce** [comment]
if context path is configured with / then return url from paypal will contain // causing spring to reject this url
see https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#request-matching

Quiqc workaround is to modify com/salesmanager/core/business/modules/integration/payment/impl/PayPalExpressCheckoutPayment.java

replace
`.append(store.getDomainName()).append("/")`
with
`.append(store.getDomainName())`

**Comment by shopizer-ecommerce** [comment]
Fixed in 2.5.0

**Comment by hungtrquoc** [comment]
still not fixing.

**Comment by shopizer-ecommerce** [comment]
It required backend code also when using no slash, not only configuration in admin page, let me know if you had a chance to test in 2.5.0

**Comment by skuch89** [comment]
I see this said as being fixed as of 2.5.0, however as of 2.12.0 version, still see this error (attached).

I see code in /sm-core/src/main/java/com/salesmanager/core/business/modules/integration/payment/impl/PayPalExpressCheckoutPayment.java:

![AppendSlashForContext](https://user-images.githubusercontent.com/11564716/82738262-4c287e00-9d2e-11ea-8504-517ba10bbad7.PNG)

Above code is suggesting of additional slash provided, if "CONTEXT_PATH" is not configured. I'm not sure, why CONTEXT_PATH is used for, though. Looks like all other parts of shopizer working okay, without "CONTEXT_PATH" being configured.
Guess, it might be conditional, e.g.:

`
String contextPath = coreConfiguration.getProperty("CONTEXT_PATH", "sm-shop");
if ( contextPath != "" )
{
    RETURN_URL.append("/").append(contextPath);
}
`
or something similar.

BTW, checked code, looks like default variable "sm-shop" would not be used, if "CONTEXT_PATH" is configured as empty (maybe expected, but).

![OverrideDefaultValueEmpty](https://user-images.githubusercontent.com/11564716/82738411-36678880-9d2f-11ea-9a1b-0a500be2987c.PNG)

**Comment by skuch89** [comment]
Forgot to attach screenshot of failure:
![PayPalTransactionFailure](https://user-images.githubusercontent.com/11564716/82738461-9e1dd380-9d2f-11ea-816b-19eeda395286.PNG)
