### ISSUE TITLE
Database design and description

### ISSUE THREAD

**Issue by waqar-ahmed** [shopizer-ecommerce/shopizer#335]
Hi,
Where can I find the database tables and their fields descriptions? Also the documentation for the modules what they are doing?
Thanks.

**Comment by shopizer-ecommerce** [comment]
Ongoing docs not yet official

https://docs.google.com/document/d/16hUvCYIpm7L5Dky_kh85wmU5fT5dlwkDbvoNHufVb6c/edit?usp=sharing
https://docs.google.com/document/d/1tulYLbPesbExaDsK19zZiyXVFYe6oYZWKCZoZ-TPOqI/edit?usp=sharing
