### ISSUE TITLE
Can not input information of cc when implement braintree

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#339]
I try to config braintree payment. This is my sanbox braintree:
![image](https://user-images.githubusercontent.com/4296584/57573343-6ad41380-7450-11e9-9b0c-bb8319162a5e.png)
But, when checkout, i cannot input information of credit card. 
![image](https://user-images.githubusercontent.com/4296584/57573367-de762080-7450-11e9-9400-48b99964adfe.png)

**Comment by shopizer-ecommerce** [comment]
Have you filled in address and all other fields before credit card number ?

**Comment by hungtrquoc** [comment]
yup, i have filled all fields before credit card.
I have tried to change tag div to input. I can input the information of cc. 
This is error after submit order. I think some bugs in braintree.jsp
![image](https://user-images.githubusercontent.com/4296584/57633197-5ec19080-75cd-11e9-8aef-e016530d5b16.png)

**Comment by shopizer-ecommerce** [comment]
Have you double check your braintree account infos, looks like an instance cannot be created

**Comment by hungtrquoc** [comment]
There are informations in my sanbox braintree. I think it is correct
![image](https://user-images.githubusercontent.com/4296584/57634412-7437ba00-75cf-11e9-82e6-28586e34f600.png)
![image](https://user-images.githubusercontent.com/4296584/57634482-96c9d300-75cf-11e9-8bd3-18e05453cdb7.png)

**Comment by shopizer-ecommerce** [comment]
ok, let me check your account on my side

**Comment by hungtrquoc** [comment]
Hi. How about this issue?

**Comment by shopizer-ecommerce** [comment]
II works on my side with sandbox and production, will test your sandbox keys, which browser are you using

**Comment by hungtrquoc** [comment]
I'm using Google Chrome browser. I cloned version 2.5.0, run without any modified code. It's still not working.

**Comment by shopizer-ecommerce** [comment]
For braintree the code generates a form using their api, can you inspect in the pages, you will see their code generated, it might indicate the reason why this field cannot be rendered

**Comment by shopizer-ecommerce** [comment]
Oh i just saw that error in javascript 'cannot read property...', that refers to braintree javascript api, that means the object is not initialized properly, i suspect another error, you might have before when object was initialized. Check in the page where this object is created and log in the console if it is defined or not

**Comment by shopizer-ecommerce** [comment]
A javascript error with google component conflicts with braintree javascript api

**Comment by shopizer-ecommerce** [comment]
Fixed https://github.com/shopizer-ecommerce/shopizer/pull/163/commits/bf6c83aae5c7518efae5cd966ae165bb79b3687b
