### ISSUE TITLE
web display duplicate user who own multi group rights

### ISSUE THREAD

**Issue by qingmo** [shopizer-ecommerce/shopizer#340]
![image](https://user-images.githubusercontent.com/2457285/57744597-6fbcef80-76fc-11e9-9fe6-ad82f20451e3.png)

**Comment by qingmo** [comment]
i'll fix it

**Comment by shopizer-ecommerce** [comment]
Ok i am looking at this, just wondering the use case, have multiple users with multiple groups ?
