### ISSUE TITLE
null ponter error when changing to national currency format while placing order

### ISSUE THREAD

**Issue by manishbka** [shopizer-ecommerce/shopizer#35]
issue:-
when we changes the store setting on admin panel as below,
store-->national currency format--> and checked the box (National currency format ex $1,345.79 or International currency format ex USD1,345.79). 
after saving and restarting the tomcat applcaition server.we gets error while checking out the cart.

we cant place order once changing to national currency format

error logs is below:-

com.salesmanager.core.business.generic.exception.ServiceException: java.lang.NullPointerException at com.salesmanager.core.business.order.service.OrderServiceImpl.caculateOrderTotal(OrderServiceImpl.java:342) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) at com.sun.proxy.$Proxy117.caculateOrderTotal(Unknown Source) at com.salesmanager.web.shop.controller.order.facade.OrderFacadeImpl.calculateOrderTotal(OrderFacadeImpl.java:204) at com.salesmanager.web.shop.controller.order.facade.OrderFacadeImpl.calculateOrderTotal(OrderFacadeImpl.java:160) at com.salesmanager.web.shop.controller.order.ShoppingOrderController.displayCheckout(ShoppingOrderController.java:311) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:212) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) at

**Comment by shopizer-ecommerce** [comment]
Fixed in 2.0.3
