### ISSUE TITLE
Breadcrumb base URL does not respect port setting from Docker Container

### ISSUE THREAD

**Issue by dividebyzero** [shopizer-ecommerce/shopizer#351]
Using 2.6.0
Howto Reproduce:
docker run -p 8099:8080 shopizerecomm/shopizer

Navigate to details of any product.
click on breadcrumb for home or category.
url will point to localhost:8080 instead of localhost:8099
observed that it is only the breadcrumbs, other links are generated ok.

Am trying to build a fix, pointers where to look first appreciated.

**Comment by sateesh2020** [comment]
![image](https://user-images.githubusercontent.com/5172059/62056443-41e74180-b23b-11e9-8361-b3a2228c3f5d.png)
The easiest way to solve this is, to change the configuration in admin in store tab. and restart the application.

**Comment by shopizer-ecommerce** [comment]
Easiest way would be to configure store base url dynamically, will add changes
