### ISSUE TITLE
Can we load `"/static/products/DEFAULT/NK022/SMALL/IMG_0248_burned.jpg"` image in a non jsp page

### ISSUE THREAD

**Issue by sateesh2020** [shopizer-ecommerce/shopizer#352]
lets say that we want to build an application, using the shop APIs , is there a way to load the images that were uploaded.

**Comment by shopizer-ecommerce** [comment]
From the api you have access to what was loaded from the console and from console you have access to what was loaded from the api
    On Thursday, July 25, 2019, 08:05:47 a.m. GMT-4, Satheesh Valluru <notifications@github.com> wrote:  
 
 
lets say that we want to build an application, using the shop APIs , is there a way to load the images that were uploaded.

**Comment by sateesh2020** [comment]
Didn't got your point :(

**Comment by shopizer-ecommerce** [comment]
yes you can load the url from non jsp :-)
