### ISSUE TITLE
Can add a negative number of quantities produce in shopping cart

### ISSUE THREAD

**Issue by hankabecirovic** [shopizer-ecommerce/shopizer#355]
Number of added products in the cart should be positive
Steps to reproduce:
1. Open single product preview page
2. Add product to the cart
3. Open shopping cart then you will see that quantities field can use a negative numbers

**Comment by BrandonBocheng** [comment]
And the total price cannot be changed according to the quantity of the commodity
<img width="1151" alt="截屏2019-10-20下午4 33 09" src="https://user-images.githubusercontent.com/42810939/67166107-942b9080-f35a-11e9-92b1-de2676133573.png">

**Comment by BrandonBocheng** [comment]
One possible approach is changing the input type of the quantity from "number" to "tel" in the jsp file.

**Comment by MasashiKishimoto** [comment]
> One possible approach is changing the input type of the quantity from "number" to "tel" in the jsp file.

This is very helpful for my work! Well done!

**Comment by shopizer-ecommerce** [comment]
Closed with PR #425
