### ISSUE TITLE
Source option 5 is no longer supported. Use 6 or later.

### ISSUE THREAD

**Issue by keanesf** [shopizer-ecommerce/shopizer#360]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shopizer 2.7.0:
[INFO] 
[INFO] shopizer ........................................... SUCCESS [  0.905 s]
[INFO] sm-core-model ...................................... SUCCESS [  3.616 s]
[INFO] sm-core-modules .................................... FAILURE [  0.197 s]
[INFO] sm-core ............................................ SKIPPED
[INFO] sm-shop-model ...................................... SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.629 s
[INFO] Finished at: 2019-09-16T21:19:04-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sm-core-modules: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.

$ mvn --version
Apache Maven 3.6.1
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8

Branch = 2.7.0

**Comment by keanesf** [comment]
I resolved the issue with the following change. 

$ git diff
diff --git a/sm-core-modules/pom.xml b/sm-core-modules/pom.xml
index 3cc7aaee..d16f2ad1 100644
--- a/sm-core-modules/pom.xml
+++ b/sm-core-modules/pom.xml
@@ -65,8 +65,8 @@
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <configuration>
-                                       <source>${java-version}</source>
-                                       <target>${java-version}</target>
+                                       <source>${maven.compiler.source}</source>
+                                       <target>${maven.compiler.target}</target>
                                </configuration>
                        </plugin>

**Comment by shopizer-ecommerce** [comment]
Ok thanks will look at this in details

**Comment by keanesf** [comment]
ok, let me know if you want me to submit a pull request with the change.

**Comment by shopizer-ecommerce** [comment]
Will be available in upcoming 2.8.0. Will close this issue
