### ISSUE TITLE
Add a manufacturer to a product

### ISSUE THREAD

**Issue by jesusPro89** [shopizer-ecommerce/shopizer#362]
I'm trying to add a manufacturer to a product but it doesn't work. 
I am using Shopizer Version 2.7.0 product-api (update and created ws funtions(POST and PATCH private)) . 
It's the only thing that has given me trouble
Who has an example of how it is done for add a manufacturer to product .

 Thanks for everything...

**Comment by shopizer-ecommerce** [comment]
Here is an example
{
    "price": 25.99,
    "quantity": 55,
    "sku": "REF12978",
    "available": true,
    "visible": true,
    "specifications": {
        "length": 10,
        "width": 20,
        "height": 30,
        "weight": 14,
        "model": "abce3456",
        **"manufacturer": "DEFAULT"**
    },
...

Need to specify manufacturer code as part of product specification

**Comment by shopizer-ecommerce** [comment]
This issue wil be closed since resolution was provided in sample below
