### ISSUE TITLE
hi, it is unfriendly to show it .

### ISSUE THREAD

**Issue by ouzhrm** [shopizer-ecommerce/shopizer#365]
![image](https://user-images.githubusercontent.com/27937775/68580307-0e11ee00-04b1-11ea-8571-25a76d4aeca0.png)

**Comment by ouzhrm** [comment]
in addition, Is there a large number of visitors to the website? i think It doesn't support a lot of traffic.

**Comment by shopizer-ecommerce** [comment]
Thanks for the comment, looking at the issue now. 

Mid high traffic on demo site

**Comment by shopizer-ecommerce** [comment]
Thanks, looking at this

Mid size to high traffic on demo site based on visting hour

**Comment by shopizer-ecommerce** [comment]
Demo has changed, issue will be closed
