### ISSUE TITLE
when maven install can not find shopizer:shopizer-shipping-distance-processor:jar

### ISSUE THREAD

**Issue by aboutdata** [shopizer-ecommerce/shopizer#37]
Failed to execute goal on project      sm-core:       Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.3-SNAPSHOT: Failure to find       com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1        in http://maven.springframework.org/milestone was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.milestone has elapsed or updates are forced -> [Help 1]

this artifactId can not found.

 		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>shopizer-shipping-distance-processor</artifactId>
			<version>0.0.1</version>
               </dependency>

**Comment by umeshawasthi** [comment]
For this time, comment this dependency from the pom.xml and it should work for you

**Comment by muzammilhussnain14** [comment]
I'm unable to install kindly help me with this error.
[ERROR] Failed to execute goal on project sm-core-modules: Could not resolve dependencies for project com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sm-core-modules
