### ISSUE TITLE
Can't find Customer login link

### ISSUE THREAD

**Issue by satishvarmadandu** [shopizer-ecommerce/shopizer#38]
Deployed Shopizer to my tomcat. Build & Deployment process is pretty smooth with no issues. But once the site is online , i can't see the login link or My Account or a way to create a new customer from the site. Do i need to enable something ? 

http://localhost:8080/sm-shop/shop 

Any help would be great  
![shopizer](https://cloud.githubusercontent.com/assets/1900021/9286527/6d4ef37c-42aa-11e5-8a30-13b5df27831c.png)

**Comment by shopizer-ecommerce** [comment]
This is not an issue, you need to activate that link from the admin panel. Right click on 'Configurations' in the admin section

**Comment by sawnwink** [comment]
Does right click works? I also face the same problem.. no SIGNIN link  at all.

**Comment by Emma04** [comment]
you have to go to localhost:8080/admin and in the configuration you activated it ;)
