### ISSUE TITLE
Add Index on CONTENT.CODE to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [shopizer-ecommerce/shopizer#383]
Missing index on table `CONTENT` column `CODE` might make the underlying query issued via [ContentService#getByCode(String, MerchantStore)](https://github.com/shopizer-ecommerce/shopizer/blob/e22152ad56b9d74d968a65293eaae94e9834003e/sm-core/src/main/java/com/salesmanager/core/business/services/content/ContentService.java#L40) slow. Since table `CONTENT` is mostly read by normal user and some times inserted or updated by the admin, the performance impact for write operations is acceptable under common cases.

**Comment by shopizer-ecommerce** [comment]
done in pr https://github.com/shopizer-ecommerce/shopizer/pull/384
