### ISSUE TITLE
Reduce the amount of data retrieved for MerchantStoreController.pageStores

### ISSUE THREAD

**Issue by wtune** [shopizer-ecommerce/shopizer#387]
For [MerchantStoreController.java#L107](https://github.com/shopizer-ecommerce/shopizer/blob/master/sm-shop/src/main/java/com/salesmanager/shop/admin/controller/merchant/MerchantStoreController.java#L107), stores with all properties are retrieved from the database, but for each store, only three properties `code`, `storename` and `storeEmailAddress` are accessed in the following business logic. In such case, retrieval of redundant properties which never used might be eliminated here.

**Comment by shopizer-ecommerce** [comment]
PR
https://github.com/shopizer-ecommerce/shopizer/pull/388
