### ISSUE TITLE
Unable to install Syntax error, annotations are only available if source level is 5.0

### ISSUE THREAD

**Issue by muzammilhussnain14** [shopizer-ecommerce/shopizer#39]
I'm getting errors while installing through $mvn clean install

[INFO] --- aspectj-maven-plugin:1.2:compile (default) @ sm-shop ---
[ERROR] Syntax error, annotations are only available if source level is 5.0
[ERROR] The type AbstractDataPopulator is not generic; it cannot be parameterized with arguments <ShoppingCartData, ShoppingCart>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] Syntax error, annotations are only available if source level is 5.0
[ERROR] The operator > is undefined for the argument type(s) Long, int
[ERROR] The type List is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type Set is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type HashSet is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] Syntax error, 'for each' statements are only available if source level is 5.0
[ERROR] The type Set is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] Syntax error, 'for each' statements are only available if source level is 5.0
[ERROR] Incompatible operand types long and Long
[ERROR] The method setQuantity(Integer) in the type ShoppingCartItem is not applicable for the arguments (int)
[ERROR] The type Set is not generic; it cannot be parameterized with arguments <ShoppingCartAttributeItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type Set is not generic; it cannot be parameterized with arguments <ShoppingCartAttributeItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type HashSet is not generic; it cannot be parameterized with arguments <ShoppingCartAttributeItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type List is not generic; it cannot be parameterized with arguments <ShoppingCartAttribute>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] Syntax error, 'for each' statements are only available if source level is 5.0
[ERROR] Syntax error, 'for each' statements are only available if source level is 5.0
[ERROR] Incompatible operand types long and Long
[ERROR] The type Set is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type HashSet is not generic; it cannot be parameterized with arguments <ShoppingCartItem>
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The method getById(Serializable) in the type SalesManagerEntityService is not applicable for the arguments (long)
[ERROR] Syntax error, parameterized types are only available if source level is 5.0
[ERROR] The type ArrayList is not generic; it cannot be parameterized with arguments <ReadableProduct>
.
.
.
.
.and so on :-(
kindly guide me on this issue

**Comment by umeshawasthi** [comment]
I am assuming you are using 2.0.2, take the update and it should work.. I have added ${java-version} in the pom.xml as aspectj-maven-plugin have some known issue.

**Comment by muzammilhussnain14** [comment]
@umeshawasthi  Thanks for your kind reply but where is update hosted ? as I think 2.0.2 was the latest code which I could get from githubh kindly can you share link.
I will be thankful

**Comment by muzammilhussnain14** [comment]
@umeshawasthi  Thanks brother I have downloaded master and now I will try to compile that and kindly can you refer me some good video tutorial to learn java spring framework as I'm in start of my career and I'm looking forward my future in java enterprise and many people recommended spring framework. Thanks for your kind reply

**Comment by muzammilhussnain14** [comment]
Mvn clean install master getting this dependence error
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.3-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-search:jar:0.0.5-SNAPSHOT, com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1: Failure to find com.shopizer:sm-search:jar:0.0.5-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
