### ISSUE TITLE
Multi-Vendor?

### ISSUE THREAD

**Issue by billiemead** [shopizer-ecommerce/shopizer#394]
Hi, does the store support setting up a Marketplace where users can register as sellers?

Cheers~

**Comment by adityakumakale** [comment]
+1 I am interested in this feature too.

**Comment by shopizer-ecommerce** [comment]
Yes api supports this. Default store is your marketplace and other stores can be added to your marketplace

**Comment by shopizer-ecommerce** [comment]
Will close this 'question'
