### ISSUE TITLE
Cannot remove products having product options from shopping cart

### ISSUE THREAD

**Issue by rasmara-rasheed** [shopizer-ecommerce/shopizer#409]
Products having product option attributes cannot be removed from shopping cart,

**Comment by shopizer-ecommerce** [comment]
Ok i see, will fix this asap, seems to be reintroduced lately

**Comment by shopizer-ecommerce** [comment]
Fixed in master branch, will be deployed as version 2.11.0 on March 30th

https://github.com/shopizer-ecommerce/shopizer/commit/22720ef25f7cb669e069282ba1d64d126fabfb12
