### ISSUE TITLE
HTTP Status 500 - Request processing failed; nested exception

### ISSUE THREAD

**Issue by hayaksu** [shopizer-ecommerce/shopizer#43]
Dears, 
After building and moving sm-shop.war to Tomcat webapps folder and then accessing the url:
http://localhost:8080/sm-shop/shop

I'm facing this error

HTTP Status 500 - Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not open connection

So, what is the problem, can anybody help ?

**Comment by umeshawasthi** [comment]
This generally means that you had database connection failure either due to database server being unavailable or an underlying network issue

Check if database is up and running and also the DB configuration in shopizer are correct or not

**Comment by hayaksu** [comment]
What I did to solve this issue is 
Uncomment H2 database config and comment out MySQL config in database.properties.
but then it shows home page with empty content, I need a sample data in order to check it functionality.
any suggestion ?

**Comment by wo3002807** [comment]
You  should create databases in the specify host ,and also modify the configuration about the database, 
I have encountered that problem. Now I solve that.
1th: Create Database name in your host.
2th: Modify the configuration about the connection to db. This file name is "database.properties"

**Comment by umeshawasthi** [comment]
Closing this issue as this seems to be setup issue
