### ISSUE TITLE
Customer email not unique?

### ISSUE THREAD

**Issue by skuch89** [shopizer-ecommerce/shopizer#434]
https://github.com/shopizer-ecommerce/shopizer/blob/5412c998af503796f4e0753fb14557bb81e7303b/sm-core-model/src/main/java/com/salesmanager/core/model/customer/Customer.java#L80

I'm wondering, looking on the previous e-commerce websites I worked on, why would email not be unique  in design?
I haven't checked on updated 2.12 shopizer version yet, but when investigated code on previous v2.9 branch shopizer allowed to create anonymous orders on registered customer's email. I don't see much benefits of this:/ Maybe some other issues(expected?) also exist (I think shopizer also creates local login for such anonymous users).

**Comment by shopizer-ecommerce** [comment]
Reviewed and fixed in 2.13.0
https://github.com/shopizer-ecommerce/shopizer/tree/2.13.0
