### ISSUE TITLE
Java compiler version

### ISSUE THREAD

**Issue by AnkurArohi** [shopizer-ecommerce/shopizer#436]
A very straightforward query, does shopizer compile in openjdk11?

**Comment by mikemainguy** [comment]
Not, not unless you add the javax depenencies, they were removed in java 11.  see here https://blog.codefx.org/java/java-11-migration-guide/.   Would a version of this for java 11 be a good idea?

**Comment by shopizer-ecommerce** [comment]
Now java11 yes openjdk11
