### ISSUE TITLE
Need Document

### ISSUE THREAD

**Issue by vincentlouis** [shopizer-ecommerce/shopizer#45]
Hi Team,

I am trying to customize the template, if possible can you please send dme the step by step document.

Thanks,
Vincent Louis

**Comment by shopizer-ecommerce** [comment]
Vincent i am doing a video tutorial on this but it is not quite ready. Version 3.0.3 will be released in the upcoming days and a brand new template will be available which is easier to understand and can be used as a baseline.

Thanks for your patience

**Comment by aamol** [comment]
Has there been any update on this. Want to use shopizer but cannot do much without documentation. Development gets very slow if someone needs to go through code for each and every thing.

**Comment by shopizer-ecommerce** [comment]
we are keeping the documentation here http://shopizer-ecommerce.github.io/shopizer/
