### ISSUE TITLE
Does shopozer support multi-vendor feature to build a marketplace like Amazon?

### ISSUE THREAD

**Issue by vishalzanzrukia** [shopizer-ecommerce/shopizer#459]
Hi, 

I have gone through this documentation : https://shopizer-ecommerce.github.io/documentation/#/software/vendors

Above seems it support multi stores with multiple vendors, but my question is, 

Does this support any functionality/add-on to build **multi-vendor** marketplace with **single** store like amazon? If yes, is there any official documentation link? Thank you in advance.

**Comment by shopizer-ecommerce** [comment]
@vishalzanzrukia Api supports multiple vendors B2B allowing the creation of multiple stores (amazon stores use case)

Also still by using the api you can have customers to upload products (ebay use case)

So building for single store this kind of works but some backend queries are not enabled yet. This is part of 2020 Q3 of our roadmap. It is on the way

**Comment by shopizer-ecommerce** [comment]
I will close this question
