### ISSUE TITLE
error while building shopizer 2.0.2

### ISSUE THREAD

**Issue by rahul2001** [shopizer-ecommerce/shopizer#46]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

C:\shopizer\shopizer>mvn clean install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be u
nique but found duplicate declaration of plugin org.bsc.maven:maven-processor-pl
ugin @ com.shopizer:sm-core-model:[unknown-version], C:\shopizer\shopizer\sm-cor
e-model\pom.xml, line 426, column 13
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] shopizer
[INFO] sm-core
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-shop
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building shopizer 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ shopizer ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ shopizer ---
[INFO] Installing C:\shopizer\shopizer\pom.xml to C:\Users\customer\.m2\reposito
ry\com\shopizer\shopizer\2.0.2-SNAPSHOT\shopizer-2.0.2-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.asp
ectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org
.aspectj:aspectjweaver:jar:1.5.4
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core ---
[INFO] Deleting C:\shopizer\shopizer\sm-core\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core --
-
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 40 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core ---
[INFO] Compiling 268 source files to C:\shopizer\shopizer\sm-core\target\classes

[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm
-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-co
re ---
[INFO] Compiling 28 source files to C:\shopizer\shopizer\sm-core\target\test-cla
sses
[INFO]
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core ---
[INFO] Building jar: C:\shopizer\shopizer\sm-core\target\sm-core-2.0.2-SNAPSHOT.
jar
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core ---
[INFO] Installing C:\shopizer\shopizer\sm-core\target\sm-core-2.0.2-SNAPSHOT.jar
 to C:\Users\customer\.m2\repository\com\shopizer\sm-core\2.0.2-SNAPSHOT\sm-core
-2.0.2-SNAPSHOT.jar
[INFO] Installing C:\shopizer\shopizer\sm-core\pom.xml to C:\Users\customer\.m2\
repository\com\shopizer\sm-core\2.0.2-SNAPSHOT\sm-core-2.0.2-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-model 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.asp
ectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org
.aspectj:aspectjweaver:jar:1.5.4
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core-model ---
[INFO] Deleting C:\shopizer\shopizer\sm-core-model\target
[INFO]
[INFO] --- maven-processor-plugin:3.1.0-beta1:process (process) @ sm-core-model
---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 1.1.1.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotat
ion processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than
-source '1.7'
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotat
ion processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source
'1.7'
[WARNING] diagnostic: warning: The following options were not recognized by any
processor: '[addSuppressWarningsAnnotation]'
[INFO]
[INFO] --- maven-processor-plugin:3.1.0-beta1:process (default) @ sm-core-model
---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 1.1.1.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotat
ion processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than
-source '1.7'
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotat
ion processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source
'1.7'
[INFO]
[INFO] --- maven-apt-plugin:1.0.2:process (default) @ sm-core-model ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-mo
del ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\shopizer\shopizer\sm-core-model\sr
c\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core-model
 ---
[INFO] Compiling 290 source files to C:\shopizer\shopizer\sm-core-model\target\c
lasses
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm
-core-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\shopizer\shopizer\sm-core-model\sr
c\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-co
re-model ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-model ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core-model ---
[INFO] Building jar: C:\shopizer\shopizer\sm-core-model\target\sm-core-model-2.0
.2-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-model
---
[INFO] Installing C:\shopizer\shopizer\sm-core-model\target\sm-core-model-2.0.2-
SNAPSHOT.jar to C:\Users\customer\.m2\repository\com\shopizer\sm-core-model\2.0.
2-SNAPSHOT\sm-core-model-2.0.2-SNAPSHOT.jar
[INFO] Installing C:\shopizer\shopizer\sm-core-model\pom.xml to C:\Users\custome
r\.m2\repository\com\shopizer\sm-core-model\2.0.2-SNAPSHOT\sm-core-model-2.0.2-S
NAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-modules 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core-modules ---
[INFO] Deleting C:\shopizer\shopizer\sm-core-modules\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-mo
dules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\shopizer\shopizer\sm-core-modules\
src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core-modul
es ---
[INFO] Compiling 12 source files to C:\shopizer\shopizer\sm-core-modules\target\
classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm
-core-modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\shopizer\shopizer\sm-core-modules\
src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-co
re-modules ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-modules ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core-modules ---
[INFO] Building jar: C:\shopizer\shopizer\sm-core-modules\target\sm-core-modules
-2.0.2-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-module
s ---
[INFO] Installing C:\shopizer\shopizer\sm-core-modules\target\sm-core-modules-2.
0.2-SNAPSHOT.jar to C:\Users\customer\.m2\repository\com\shopizer\sm-core-module
s\2.0.2-SNAPSHOT\sm-core-modules-2.0.2-SNAPSHOT.jar
[INFO] Installing C:\shopizer\shopizer\sm-core-modules\pom.xml to C:\Users\custo
mer\.m2\repository\com\shopizer\sm-core-modules\2.0.2-SNAPSHOT\sm-core-modules-2
.0.2-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-shop 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.shopizer:sm-core:jar:2.0.2 is missing, no dependency i
nformation available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] shopizer ........................................... SUCCESS [  0.294 s]
[INFO] sm-core ............................................ SUCCESS [  7.905 s]
[INFO] sm-core-model ...................................... SUCCESS [  7.648 s]
[INFO] sm-core-modules .................................... SUCCESS [  0.625 s]
[INFO] sm-shop ............................................ FAILURE [  0.215 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.819 s
[INFO] Finished at: 2015-09-11T17:55:16+05:30
[INFO] Final Memory: 63M/168M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencie
s for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find com.s
hopizer:sm-core:jar:2.0.2 in http://maven.springframework.org/milestone was cach
ed in the local repository, resolution will not be reattempted until the update
interval of org.springframework.maven.milestone has elapsed or updates are force
d -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :sm-shop

**Comment by umeshawasthi** [comment]
Please test with latest 2.0.3, this has been fixed with 2.0.3
