### ISSUE TITLE
error while building sm-shop

### ISSUE THREAD

**Issue by rahul2001** [shopizer-ecommerce/shopizer#47]
[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencie
s for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find com.s
hopizer:sm-core:jar:2.0.2 in http://maven.springframework.org/milestone was cach
ed in the local repository, resolution will not be reattempted until the update
interval of org.springframework.maven.milestone has elapsed or updates are force

pls help me regarding this

**Comment by umeshawasthi** [comment]
This has been fixed with 2.0.3, please retest with 2.0.3
