### ISSUE TITLE
"commitOrder" API wrongly updates the inventory

### ISSUE THREAD

**Issue by wecache** [shopizer-ecommerce/shopizer#477]
## Problem

Two customers can buy the same product (by submitting the order), but the quantity of the product is only decreased by one.

More seriously, two customers can buy the same product, even if the product's available quantity is one.

## Summary of the cause of the bug

Shopizer uses the same hibernate session for handling one API, like "commitOrder". The "commitOrder" API has multiple transactions that share the same hibernate session. Meanwhile, hibernate uses its L1 cache by default to cache the records read from the database for each session, and the L1 cache is not invalidated after a transaction commits.

Therefore, it is possible that some subsequent transaction's read operation (etc., entityManager.find()) gets the record from the L1 cache rather than the database. Then there might be another API modifies the cached record, and causes **inconsistency between cache and database**.

In this issue, the transaction (OrderServiceImpl.processOrder()), which is responsible for checking the available quantity of product, reads a stale product quantity from the cache and wrongly passes the check.

## How to reproduce the bug (step-by-step)

Shopizer Version: 2.12.0

Git Commit number: 64aa5fdb

### Preparation

* Run the ShopApplication as what Readme suggested.
* In the ''/admin" site, modify the "quantity available" of product "Spring in Action" (in this example) to one.
  * Login admin.
  * Enter the web page managing the details of product "Spring in Action".
    * Click Catalogue->Products->Root->Computer Books->Web.
    * Find "Spring in Action", and click details.
  * Modify the "quantity available" to one, and then click the "submit" button.

* Open two browsers to emulate two customers, called A and B, respectively (the sub-steps should be done on each browser)
  * Register the customer, A or B, and login.
  * Add "Spring in Action" to the shopping cart
    * Click "Home", and jump to the home page.
    * Click the "Add to cart" button under Spring in Action.
  * Prepare to submit the order
    * Click "Shopping cart" on the up-right of the homepage, and then click "checkout".
    * Click "PROCEED TO CHECKOUT"
    * In the Checkout page, fill the necessary information blanks

### Trigger the bug

* Add a breakpoint to function OrderServiceImpl.processOrder(), which is called when order is submitted.
  * The breakpoint should be set to (sm-core/src/main/java/com/salesmanager/core/business/services/order/OrderServiceImpl#Line194)
  * The Following code of (OrderServiceImpl#Line194) is to check whether the available quantity of each product is enough
    * If the available quantity is not enough, the code will throw an "EXCEPTION_INVENTORY_MISMATCH".
* Click "submit order" on two browsers, and let the two threads, which handle A and B's request, execute to the breakpoint.
* Let two threads execute to Line 202, which compares the requested quantity of the order and the available quantity.
* **The bug happens!**
  * For the two threads, they all observe the available quantity is 1 and can pass the check.
  * As a result, the orders of two customers can both succeed.

## Possible Solution

* Use entityManager.reload() function to forcely read products from the database.

**Comment by sejno** [comment]
Important to ensure performance, reload of quantity only reload the product being affected!

**Comment by wecache** [comment]
Hi.

## Supplement of issue
The root cause of this problem is that: the transaction, which is used to update quantity, may read the stale ProductAvailability record from L1 Cache. It is because in the same hibernate session, there was a transaction that had read the ProductAvailability record from the database and store it in L1 Cache.

However, L1 Cache won't know if transactions in other sessions concurrently update the record, and thus make the record in L1 Cache stale. In the above example, the second customer who buys the same product would observe that quantity is still 1 although it has been bought by the first customer.

Hibernate allows different transactions in a session shared the per-session L1 Cache. When a transaction tries to read data stored in L1 Cache by other transactions in the same session, to avoid reading the stale record, the transaction should reload the record and retrieve it from the database. Otherwise, it may cause anomalies as the example given. 

## Reply to @sejno
1. If we can detect which products are affected, it is nice to only reload the affected product for performance. However, in the above example, there is no method that can notify the transaction of the second customer which products are affected, so it has to reload all the products for correctness.

2. No matter whether the method (update quantity logic) is written correctly, the above incorrect example would make the method behave inconsistently with its code, due to the productAvailaiblity in the L1 cache might be stale.

3. Even if the process of checkout and update quantity is efficient (takes little time to finish), it is still possible that the incorrect example takes place. Making the process efficient can only reduce the possibility of the problem rather than solve the problem.

4. Without cache, the app logic (decrease in ProductAvailability object) is correct. It can prevent the above incorrect example (one of the two customers will get an exception), because it is protected by the database transaction. If we use reload, the app logic is correct even with the cache.

By the way, "deferring the decrease of ProductAvailability until physical stock is recalculated" seems not able to prevent the above incorrect example, because the checking can not be deferred and it can still be based on the stale productAvailiability quantity.
