### ISSUE TITLE
Question : Support for product variants

### ISSUE THREAD

**Issue by yajnasteju** [shopizer-ecommerce/shopizer#488]
Hi,

Im just exploring shopizer for an e commerce store.
I have a particular question about supporting product variants.

If i need to sell t shirts , in product detail page  i need to show various sizes and colors available, and i dont see that feasibility in the demo.

Is this achievable in shopizer?
This should be a basic requirement for any e commerce platform.

**Comment by shopizer-ecommerce** [comment]
Yes it is supported

Those are options

http://aws-demo.shopizer.com:8080/shop/product/asian-table-standard.html
