### ISSUE TITLE
Build Failure for ProductTest class

### ISSUE THREAD

**Issue by devangadeshara** [shopizer-ecommerce/shopizer#490]
Hi Team,

    I have facing this issue since long. This issue is an assertion failed in my machine.  I have debugged more and found the error in ProductTest.java class in sm-core. 

In the method
`private void testAttributes(Product product) throws Exception {} `
it shows the error at below line.
` Assert.assertEquals(new Long(attributes.size()).longValue(), 3l);`

Step to reproduce in windows machine
- [ ] git clone shopizer

- [ ] cd shopizer 

- [ ] mvn clean install

which will throws below error

> [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.233 s <<< FAILURE! - in com.salesmanager.test.catalog.ProductTest
[ERROR] testCreateProduct  Time elapsed: 0.231 s  <<< FAILURE!
java.lang.AssertionError: expected:<6> but was:<3>
        at com.salesmanager.test.catalog.ProductTest.testAttributes(ProductTest.java:516)
        at com.salesmanager.test.catalog.ProductTest.testCreateProduct(ProductTest.java:338)

**Comment by meowow** [comment]
@devangadeshara Does your test fail in sequence or just when you lunch a single one?
In my case, if I  launch a single ProductTest it passes but when I launch the catalog package these tests failed.
I tried to @Ignore `testCreateProduct` and the test passed.

**Comment by devangadeshara** [comment]
@meowow, yes i am compiling entire shopizer with `mvnw clean install`. I have changed the below code and it works for me

change
` Assert.assertEquals(new Long(attributes.size()).longValue(), 3l);`
to
` Assert.assertEquals(new Long(attributes.size()).longValue(), 6l);`

**Comment by shopizer-ecommerce** [comment]
Fixed in https://github.com/shopizer-ecommerce/shopizer/commit/10873fc942f41b079afd67992a375e51337314ef
I changed attributes calculation logic, it is calculating attributes from another test
