### ISSUE TITLE
Windows OS : CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by devangadeshara** [shopizer-ecommerce/shopizer#496]
Hi Team,

    The shopizer project is not working in windows os. Steps to reproduce the error

- [ ] `git clone https://github.com/shopizer-ecommerce/shopizer`

- [ ] `mvnw clean install`

- [ ] `mvnw spring-boot:run`

I am getting below error while executing the command

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.156 s
[INFO] Finished at: 2020-10-29T19:08:10+05:30
[INFO] Final Memory: 49M/188M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.3.RELEASE:run (default-cli) on project sm-shop: Could not exec java: Cannot run program "D:\software\jdk-11.0.7\bin\java.exe" (in directory "D:\devangadeshara\shopizer\sm-shop"): CreateProcess error=206, The filename or extension is too long -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by emerson-matos** [comment]
Did you try to run with jdk 8? @devangadeshara

**Comment by dimeros** [comment]
You can try to add a fork configuration to value false in the sm-shop/pom.xml:

```
<plugin>
 	<groupId>org.springframework.boot</groupId>
 	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<fork>false</fork>
	</configuration>
 </plugin>
```

**Comment by shopizer-ecommerce** [comment]
Suggestion create your maven repo in c:\repo and change maven repo path in your settings file
