### ISSUE TITLE
creating manufacturer is giving "Field required"

### ISSUE THREAD

**Issue by rahul2001** [shopizer-ecommerce/shopizer#51]
In admin panel when i click catalogue and create manufacturer, Form shows "Field Required" and did not save the details what should i do..............

**Comment by projectmallwall** [comment]
ID and path to be modified in following code in manufacturer.jsp resolves the issue
`<form:input cssClass="input-large highlight" id="code" path="manufacturer.code" onblur="validateCode()"/>
	                                <span class="help-inline"><div id="checkCodeStatus" style="display:none;"></div><form:errors path="manufacturer.code" cssClass="error" /></span>`

**Comment by rahul2001** [comment]
Thanks

**Comment by shopizer-ecommerce** [comment]
Fixed in 2.0.3
