### ISSUE TITLE
can't import source code into eclipse

### ISSUE THREAD

**Issue by yuzhiping** [shopizer-ecommerce/shopizer#52]
when i import the source code into eclipse i met a problem as blew:i do it follows the documents, 

![qq 20151031100735](https://cloud.githubusercontent.com/assets/10362461/10861363/415e0114-7fb7-11e5-8517-dcadf2bbcbb1.png)

who can give me some advices?

**Comment by zhhaojie** [comment]
update the maven plugin that should be help

**Comment by yuzhiping** [comment]
thanks @zhhaojie ,i try it but it still not work, did you try it?

**Comment by elkad** [comment]
@yuzhiping try it!
![cap 2015-11-29 13-15-04-775](https://cloud.githubusercontent.com/assets/4374449/11455310/47736c2e-969b-11e5-9381-a7561cf31e32.png)

**Comment by yuzhiping** [comment]
@elkad i was downloaded shopizer from your Repositories and then import to Eclipse but it still had problem

**Comment by shopizer-ecommerce** [comment]
Yes it is a known issue with maven plugin in eclispse for certain versions.

It does not prevent the compile, generate source or package tasks, you can tell eclipse to ignore that error

**Comment by elkad** [comment]
@yuzhiping  Did you use branch 'develop' from my Repositories?

**Comment by yuzhiping** [comment]
@elkad  i tried but failured   now i am  doubt   the problem caused by the version of maven but the program?   which  version of maven  did you use when you build the project source?

**Comment by yuzhiping** [comment]
Which version you use maven? Maven2 or maven3?

**Comment by elkad** [comment]
@yuzhiping 
I use STS tool. so it embedded maven 3.3.3 version.
