### ISSUE TITLE
Error while building Shopizer -smcore

### ISSUE THREAD

**Issue by moorthi523** [shopizer-ecommerce/shopizer#53]
Hi,

Getting below exception while building sm-core.

E:\shopizer-2.0.2\shopizer\sm-core>mvn clean install
[INFO] Scanning for projects...
Downloading: http://maven.springframework.org/snapshot/com/shopizer/shopizer/2.0.2-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.springframework.org/snapshot/com/shopizer/shopizer/2.0.2-SNAPSHOT/shopizer-2.0.2-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.shopizer:sm-core:[unknown-version]: Could not find artifact com.shopizer:shopizer:pom:2.0.2-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) and 'parent.relativePath' points at wrong local POM @ line 6, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.shopizer:sm-core:[unknown-version] (E:\shopizer-2.0.2\shopizer\sm-core\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.shopizer:sm-core:[unknown-version]: Could not find artifact com.shopizer:shopizer:pom:2.0.2-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) and 'parent.relativePath' points at wrong local POM @ line 6, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by umeshawasthi** [comment]
This has been fixed with 2.0.3, please test with 2.0.3
