### ISSUE TITLE
Problem with java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by marinr** [shopizer-ecommerce/shopizer#54]
Hi ,

As much as I increase XX:MaxPermSize. it still fails  on PermGen space.

Thanks,
Marin

**Comment by daveyx** [comment]
Hi,

i also got PermGen space error and just added 
-XX:MaxPermSize=300m -Xmx2048m -Xms1024m
to the vm arguments...

Kind regards
davey

**Comment by umeshawasthi** [comment]
This is not related to Shopizer , you need to allocate more memory to tomcat / editor.
