### ISSUE TITLE
Angular PWA

### ISSUE THREAD

**Issue by iAbhinav** [shopizer-ecommerce/shopizer#554]
While reading about shopizer I have spotted angular demo, but I am unable to find any detail on the upcoming angular. The following queries bug me, help much appreciated.

1. When is the angular web app planned to be released?
2. Will the angular version be open-sourced?

**Comment by shopizer-ecommerce** [comment]
Hi,

We have a shop reactjs and admin angular admin projects

React shop is pretty much stable and going to beta release next week
Angular admin is on the way and should be in beta in march

Both are OSS
