### ISSUE TITLE
Not found QCategory and QCategoryDescription class!

### ISSUE THREAD

**Issue by anhdenday** [shopizer-ecommerce/shopizer#58]
Hi All,

I am new to shopizer, I just download the source code and build it, but this source code doesn't have following 2 class.
com.salesmanager.core.business.catalog.category.model.QCategory;
com.salesmanager.core.business.catalog.category.model.QCategoryDescription;

Please check it, thanks you

**Comment by daveyx** [comment]
Hi,

this class QCategory i only see only under target/generated-sources/querydsl

So i suggest to run "mvn generate-sources"

**Comment by umeshawasthi** [comment]
This has been fixed with 2.0.3, please test with 2.0.3
