### ISSUE TITLE
Needs to handle exception while checkout

### ISSUE THREAD

**Issue by ravindra-yadava** [shopizer-ecommerce/shopizer#587]
If no items are in cart and we open direct checkout page it returns exception (Should be handled). 
http://localhost:8080/shop/order/checkout.html

![image](https://user-images.githubusercontent.com/29541347/116364079-6feb2280-a821-11eb-838f-2933f7471746.png)

**Comment by shopizer-ecommerce** [comment]
Thanks, looking at it

**Comment by FelippeSilva2** [comment]
Hey i have worked on a fix for this issue on one of my forks of this project, any way i can pull request ?

**Comment by shopizer-ecommerce** [comment]
Sure @FelippeSilva2
    On Wednesday, May 12, 2021, 06:04:21 a.m. GMT-4, FelippeSilva2 ***@***.***> wrote:  
 
 


Hey i have worked on a fix for this issue on one of my forks of this project, any way i can pull request ?

**Comment by FelippeSilva2** [comment]
Pull Requested: https://github.com/shopizer-ecommerce/shopizer/pull/588
