### ISSUE TITLE
DeadLockSelector

### ISSUE THREAD

**Issue by nguyendangtu** [shopizer-ecommerce/shopizer#59]
Hi all,
I have just download, build and deploy .war to tomcat 7. When I start the project, I got an exception 
DeadLockSelector Apprent DeadLock, when loading InstrumentaionLoadTimeweaver.
Would you please help to fix this issue.
Thank you so much

**Comment by iandow** [comment]
Me too.  Reproduced in Tomcat 8, and with both Java 7 and Java 8.

**Comment by yuzhiping** [comment]
clone the lasted and recompile will be ok



发自我的小米手机
在 Ian Downard <notifications@github.com>，2016年3月2日 上午7:34写道：

Me too. Reproduced in Tomcat 8, and with both Java 7 and Java 8.

**Comment by iandow** [comment]
I can compile fine. This deadlock occurs during runtime, after deploying the war file to tomcat.  I see the deadlock in catalina.out:

http://pastebin.com/7HAmA3BG

**Comment by inderjeet** [comment]
Getting the same issue, anybody got the solution?

**Comment by inderjeet** [comment]
<prop key="POPULATE_TEST_DATA">true</prop>
Not working with both SQL and h2 databases.
When I make the value to false, it works fine.

**Comment by shopizer-ecommerce** [comment]
We did re-test 2.0.5 on tomcat 7, 8 and 9 absolutely requires Java 8 but could not get that 'DeadLockSelector' issue. Because it has been opened for a while without new addition this ticket will be closed.

**Comment by shopizer-ecommerce** [comment]
outdated
