### ISSUE TITLE
Content page cannot save

### ISSUE THREAD

**Issue by lpcclown** [shopizer-ecommerce/shopizer#615]
In the admin portal, when I try to use ckeditor to save the customized page, it cannot be saved. Only pure text content is saved. 

There are two errors showing in the console, not sure if they are related, any info is appreciated, thanks. 

![image](https://user-images.githubusercontent.com/7920916/124992617-34cf5180-e011-11eb-8e8d-377ea71726f8.png)

**Comment by guymoyo** [comment]
I faced this problem, There are 2:

1. Because CKEDITOR is not configured to allow HTML content, so you have to enable it into `config.js` with `config.allowedContent = true;`

2. SanitizeUtils.java is removing HTML content which is fine because of the strict policy of `antisamy-slashdot.xml`
You have to put something like `antisamy-ebay.xml` which is less strict. Or google Owasp antisamy to see what is best for you.

**Comment by lpcclown** [comment]
> I faced this problem, There are 2:
> 
> 1. Because CKEDITOR is not configured to allow HTML content, so you have to enable it into `config.js` with `config.allowedContent = true;`
> 2. SanitizeUtils.java is removing HTML content which is fine because of the strict policy of `antisamy-slashdot.xml`
>    You have to put something like `antisamy-ebay.xml` which is less strict. Or google Owasp antisamy to see what is best for you.

Hi @guymoyo , thanks for your reply. I checked that the "config.allowedContent" only enabled for ckeditor 4.1 version and after. I tried that, however, it does not work.

**Comment by lpcclown** [comment]
> I faced this problem, There are 2:
> 
> 1. Because CKEDITOR is not configured to allow HTML content, so you have to enable it into `config.js` with `config.allowedContent = true;`
> 2. SanitizeUtils.java is removing HTML content which is fine because of the strict policy of `antisamy-slashdot.xml`
>    You have to put something like `antisamy-ebay.xml` which is less strict. Or google Owasp antisamy to see what is best for you.

Hi @guymoyo , I tried the second point/solution, it works. Perfect. You are the hero.
