### ISSUE TITLE
Security Vulnerability - Java BigDecimal DOS

### ISSUE THREAD

**Issue by tonghuaroot** [shopizer-ecommerce/shopizer#637]
Directly incorporating user input into an BigDecimal Operation Function without validating the input
can facilitate DOS attacks. In these attacks, the server
will consume a lot of computing resources, A typical scenario is that the CPU usage rises to close to 100%.
This issue often occurs in scenarios that require scientific computing, such as e-commerce platforms and electronic payments.

Ref: https://lgtm.com/query/8526273903463417733/

**Comment by shopizer-ecommerce** [comment]
Lookig at it

**Comment by shopizer-ecommerce** [comment]
Thanks for submiting a use case scenario to help to the investigation

**Comment by shopizer-ecommerce** [comment]
Closing this issue, no BigDecimal accepted from input payloads
