### ISSUE TITLE
OpenApi spec invalid

### ISSUE THREAD

**Issue by svdbtno** [shopizer-ecommerce/shopizer#689]
I got shopizer up and running and wanted to use the OpenApi spec for some automation. However when I tried loading it in there were some issues. I opened the OpenApi with the [swagger editor](https://editor.swagger.io/) and received a bunch of errors. 
The ones that occur the most are the fields 'lang'and 'store' which are missing the 'in'-field and the schema : '#/definitions/String' does not exist. 

I tried manually fixing these errors, but that is a lot of work. Do you have any idea where to look to fix the generation of the OpenApi spec.

**Comment by shopizer-ecommerce** [comment]
https://app.swaggerhub.com/apis/shopizer/shopizer-rest-api/3.0.0

Shows multiple errors in the editor. It does not prevent working perfectly. For this we'll have to migrate to open api 3 not yet in our plan.

lang and store are swagger annotations that are not 'digested' in the editor

      @ApiImplicitParam(name = "store", dataType = "String", defaultValue = "DEFAULT"),
      @ApiImplicitParam(name = "lang", dataType = "String", defaultValue = "en")})
      
Will have to close this ticket as the runtime is not impacted and migration to openapi 3 will not happen in shopizer 3.X
