### ISSUE TITLE
Deadlock issue while deploying shop.war in Tomcat 8

### ISSUE THREAD

**Issue by vijaykumargundavarapu** [shopizer-ecommerce/shopizer#73]
Hi,

I think this issue was raised already but I did not see any solution so far in that thread. I deployed shop.war and trying to start Tomcat and it goes into some Thread deadlock.

Can you please help me with this issue?

**Comment by daveyx** [comment]
long time ago i also had a deadlock issue, but it was with 2.0.2 on java7 with tomcat7.
with 2.0.3 and java8 + tomcat8 and increasing the heapspace, i never had that issue.

**Comment by vijaykumargundavarapu** [comment]
I am using 2.0.3 with java 8+ tomcat 8 only.

I increased the heap space in catalina.bat but not sure whether I did the changes correctly.
Are these changes correct? I changed in two places below.

if not "%LOGGING_CONFIG%" == "" goto noJuliConfig
set LOGGING_CONFIG=-Dnop
if not exist "%CATALINA_BASE%\conf\logging.properties" goto noJuliConfig
set LOGGING_CONFIG=-Djava.util.logging.config.file="%CATALINA_BASE%\conf\logging.properties"
:noJuliConfig
**set "JAVA_OPTS=-Xms1024m -Xmx1024m -XX:MaxPermSize=256m" **

if not "%LOGGING_MANAGER%" == "" goto noJuliManager
set LOGGING_MANAGER=-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
:noJuliManager
**set "JAVA_OPTS=-Xms1024m -Xmx1024m -XX:MaxPermSize=256m"**

**Comment by daveyx** [comment]
i don't use windows and have set it in bin/setenv.sh but of course it can be set in catalina.sh also, i don't know how to do so in windows
i am not convinced that the deadlock occurs because of not enough heap space
java8 does not support maxpermsize anymore and you should see a message about that in the log

**Comment by umeshawasthi** [comment]
I also delpoyed it on tomcat and seen no issue.

Will do a fresh deployment on tomcat and let you know, also deadlocks are more or less server issue and not app issue

**Comment by shopizer-ecommerce** [comment]
Ok, there was a commit for using MySQL by default when it works out of the box with H2 requiring nothing to do. I have committed

https://github.com/shopizer-ecommerce/shopizer/commit/63ee08bcd951670c5f63268bc0a6b6af993be0a3


#MYSQL
#db.jdbcUrl=jdbc:mysql://localhost:3306/SALESMANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
#db.user=root
#db.password=root
#hibernate.hbm2ddl.auto=update
#db.driverClass=com.mysql.jdbc.Driver
#hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#db.preferredTestQuery=SELECT 1
#db.schema=SALESMANAGER

#H2
db.jdbcUrl=jdbc\:h2\:file\:SALESMANAGER;AUTOCOMMIT=OFF;INIT\=CREATE SCHEMA IF NOT EXISTS SALESMANAGER
db.user=test
db.password=password
db.driverClass=org.h2.Driver
hibernate.dialect=org.hibernate.dialect.H2Dialect
db.preferredTestQuery=SELECT 1
db.schema=SALESMANAGER

hibernate.hbm2ddl.auto=update

Or you can use MySQL 
https://github.com/shopizer-ecommerce/shopizer/wiki/Shopizer-configuration#Database%20configuration

**Comment by vijaykumargundavarapu** [comment]
Yep. That was the issue. It works now. Thanks

**Comment by inderjeet** [comment]
<prop key="POPULATE_TEST_DATA">true</prop>
Not working with both SQL and h2 databases.
When I make the value to false, it works fine.
