### ISSUE TITLE
My Account link in the dashboard goes nowhere when I click on it

### ISSUE THREAD

**Issue by ratneshp0** [shopizer-ecommerce/shopizer#74]
Hi Umesha,
                I had raised earlier one ticket for this My Account link, you closed it saying it is working and it will take us to the dashboard page. You are right, but when I click on this link on the dashboard.html it just doesn't go anywhere, it remains in the same dashboard.html and doesn't show any account information. Can you please help me set up this my account page when we click from the dashboard.html.

Thanks,
Ratnesh

**Comment by umeshawasthi** [comment]
@Ratnesh
Currently this is just showing dashboard again but you are free to
customize it the way you want. This dashboard just give you the idea about
the feature we are providing but you are free to customize it as per your
requirement.


On Thu, Mar 17, 2016 at 9:06 PM, ratneshp0 <notifications@github.com> wrote:

> Hi Umesha,
> I had raised earlier one ticket for this My Account link, you closed it
> saying it is working and it will take us to the dashboard page. You are
> right, but when I click on this link on the dashboard.html it just doesn't
> go anywhere, it remains in the same dashboard.html and doesn't show any
> account information. Can you please help me set up this my account page
> when we click from the dashboard.html.
>
> Thanks,
> Ratnesh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/74>
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by ratneshp0** [comment]
Can you please help me on how we can customize it. Can we do it through
admin panel. Please help I wanted this my account feature to be working for
my site.

**Comment by ratneshp0** [comment]
Please help me on how to customize this my account link.

**Comment by ratneshp0** [comment]
Please help me on how to customize this my account link.

**Comment by shopizer-ecommerce** [comment]
Can you post the error you are getting ? Can you look from firebug or any other browser javascript tool what the json response is

**Comment by ratneshp0** [comment]
I am not getting any error. When I click on it, it invokes http://localhost:8080/sm-shop/shop/customer/dashboard.html. I don't see any json response coming in. It just displays me the same page. I tried to look into the code, and it seems the code is calling getCustomerOptions method which is fetching customer option code and value. But in my case it is returning null. And the dashboard.jsp is looping through this customer options to show some name, id, and value. Now the question is, are these options going to show us the My Account details of a customer. And how we can set these if it is dependent on these parameters. The  getCustomerOptions  is querying SALESMANAGER.CUSTOMER_OPTION, SALESMANAGER.CUSTOMER_OPTION_DESC, SALESMANAGER.CUSTOMER_OPTION_VALUE and SALESMANAGER.CUSTOMER_OPT_VAL_DESCRIPTION.

Please help on this one.

thanks,
Ratnesh

**Comment by ratneshp0** [comment]
HI, 
   Can you please help me in this my account link not working. I provided the information you neeeded.

Thanks,
Ratnesh

**Comment by ratneshp0** [comment]
Hi,
    Can you please help me on this as the issue in the my account link still persists. When I click on it, it goes nowhere and stays in the dashboard.html page itself. I don't get any error and it doesn't return any json response from the dashboard.html URL.

Thanks,
Ratnesh
