### ISSUE TITLE
some error in CustomerDAOImpl

### ISSUE THREAD

**Issue by 277544276** [shopizer-ecommerce/shopizer#75]
please,when i import this project ,ide tip me  can't  find QCustomer，QCountry....

**Comment by daveyx** [comment]
try 
mvn generate-sources

actually this should be called if you run "mvn clean install" automatically

**Comment by 277544276** [comment]
it's work,tks.i need read document more clear.

**Comment by daveyx** [comment]
congratulations!

close the issue please
