### ISSUE TITLE
Missing dependency - modules-commons - 3.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by saraalways100** [shopizer-ecommerce/shopizer#780]
Missing dependency
<dependency>
            <groupId>com.shopizer</groupId>
            <artifactId>modules-commons</artifactId>
            <version>3.2.1-SNAPSHOT</version>
        </dependency>

**Comment by shopizer-ecommerce** [comment]
Unless you pulled WIP 3.2.1 branch you will not find snapshot in master branch. Will close this ticket
