### ISSUE TITLE
Missing many classes in shopizer 2.0.3?

### ISSUE THREAD

**Issue by anhdenday** [shopizer-ecommerce/shopizer#79]
Hi, 
I tried to run shopizer inside eclipse, but when I get the source code from maven and build, it's missing so many class. For example: 
com.salesmanager.core.business.catalog.product.model.QProduct;
com.salesmanager.core.business.catalog.product.model.attribute.QProductAttribute; com.salesmanager.core.business.catalog.product.model.attribute.QProductOption; com.salesmanager.core.business.catalog.product.model.attribute.QProductOptionValue; com.salesmanager.core.business.catalog.product.model.attribute.QProductOptionValueDescription;
![screen shot 2016-03-26 at 6 01 40 pm](https://cloud.githubusercontent.com/assets/6926208/14059697/1b2d613a-f37d-11e5-93b5-b13f29eed59e.png)
Even when I use "mvn generate-sources" to generate but it still missing.
Please check it.
Thanks you

**Comment by umeshawasthi** [comment]
These classes should be generated automatically during build, please run  `mvn clean install` so as build should generated these classes for you.

**Comment by anhdenday** [comment]
Hi @umeshawasthi,
Of course I did build with maven already with "mvn clean install" and even when I try with ""mvn generate-sources" to generated these classes but still missing. I dont know why.

**Comment by umeshawasthi** [comment]
These classes are autogenerated by build and that is the reason why you will not find those in the repository.

**Comment by jincieryi** [comment]
the sample problem ,i  don't know how to solve it ,too .

**Comment by beawlp** [comment]
Try maven-clean, maven-generate-sources,maven install on sm-core-model and then on maven clean and install on shopizer. You should not delete the querydsl packages from the build path as it tempt us to just delete the missing packages.

**Comment by umeshawasthi** [comment]
This is just a build issue, please make sure you are doing clean and generate source

**Comment by inderjeet** [comment]
Hi Umesh,
Is there any issue with build 2.0.3. I am able to clean and install but when I deploy this on tomcat and start tomcat getting many errors.
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:1168)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1104)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:998)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1512)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1440)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrent
Entity(XMLEntityManager.java:646)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineD
ocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.p
arse(SchemaParsingConfig.java:582)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.p
arse(SchemaParsingConfig.java:685)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse
(SchemaDOMParser.java:530)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getS
chemaDocument(XSDHandler.java:2175)
        ... 54 more
ERROR: org.springframework.web.context.ContextLoader - Context initialization fa
iled
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Config
uration problem: Failed to import bean definitions from URL location [classpath:
/spring/shopizer-core-rules.xml]
Offending resource: class path resource [spring/spring-context.xml]; nested exce
ption is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException:
Line 13 in XML document from class path resource [spring/shopizer-core-rules.xml
] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 13;
 columnNumber: 51; cvc-complex-type.2.4.c: The matching wildcard is strict, but
no declaration can be found for element 'drools:kbase'.
        at org.springframework.beans.factory.parsing.FailFastProblemReporter.err
or(FailFastProblemReporter.java:68)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderC
ontext.java:85)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderC
ontext.java:76)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentRe
ader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:248)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentRe
ader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:199)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentRe
ader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentRe
ader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:147)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentRe
ader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:101)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registe
rBeanDefinitions(XmlBeanDefinitionReader.java:495)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadB
eanDefinitions(XmlBeanDefinitionReader.java:391)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBea

**Comment by hashemyousefi** [comment]
for add generated Qclasses after clean and build project run maven this command mvn build:eclipse

**Comment by umeshawasthi** [comment]
Please use latest 2.0.4

**Comment by RameshMAloha** [comment]
Hi All, 
Some java files are missing in 2.0.2 so follow below steps to get latest.
Download below latest jar file from maven:
sm_core_model 2.0.3
sm_core_modules 2.0.3
sm-search 0.5
Just type sm_core_model 2.0.3 in google you will redirect to maven repository, so add this dependency to your sm-core and sm-shop pom.xml.
Make sure that the version should be 2.0.3.
Let me know if it make sense.

**Comment by umeshawasthi** [comment]
You need to clean and  build as these classes are auto generated during build, I suggest to move 2.0.4 which is more stable and we have done some changes in overall build process.

**Comment by radrao24** [comment]
Hi All,
I have a similar issue and I tried with both jdk 1.8 and 1.7 but still the same error.

What is the best way to upgrade from 2.0.3 to 2.0.4?

Any help would be greatly appreciated.
