### ISSUE TITLE
How much do you charge for helping in payment gateway integration

### ISSUE THREAD

**Issue by ratneshp0** [shopizer-ecommerce/shopizer#83]
Hi,
    I have set up shopizer currently in my local. I have not hosted it in any domain so far. I needed help in setting up the payment gateway before I set host it. HJow much do you guys charge for helping in setting up witht eh payment gateway like ccavenue. Please let me know if you have any phone number in India on which we can talk.

Thanks,
Ratnesh

**Comment by shopizer-ecommerce** [comment]
Can you ask on the forum those types of questions https://groups.google.com/forum/#!forum/shopizer

**Comment by ratneshp0** [comment]
I am sorry I didn't know about this forum.
