### ISSUE TITLE
Incompatible Jackson version in default configuration

### ISSUE THREAD

**Issue by mprobst** [shopizer-ecommerce/shopizer#843]
On a clean `git clone` and `./mvnw clean install`, install fails with exceptions related to a Jackson class missing:

```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
```

This appears to be due to an outdated Jackson version. Upgrading to `2.14.2` fixes the issue for me:

```
-               <jackson-version>2.10.2</jackson-version>
+               <jackson-version>2.14.0</jackson-version>
```

**Comment by shopizer-ecommerce** [comment]
Thanks completed in main branch
Sorry it was stuck between master to main branch issues fixing
