### ISSUE TITLE
login [page

### ISSUE THREAD

**Issue by vedgupta07** [shopizer-ecommerce/shopizer#94]

**Comment by developer10** [comment]
Description missing?

**Comment by waqarys** [comment]
I am unable to see login/register button for customer to register themselves. Wven in Admin->Configurations I do not see any option to enable/disable registration link. Any help is greatly appreciated.

**Comment by sawnwink** [comment]
i also face the same problem. there should be a SIGNIN link on the left of MyCart at the top right corner. But it is'nt there. Can someone advise?

**Comment by waqarys** [comment]
@sawnwink  I was able to solve the problem. Login as administrator. Go to configurations, in the last tab check the displayCustomerSection checkbox and save. If still you are not able to see Login/Register go to MERCHANT_CONFIGURATION table and see the values present in CONFIG_KEY, VALUE and TYPE column.
Hope you will be able to login/register.

**Comment by sawnwink** [comment]
@waqarys i did just that.. and in the db: my value is {"debugMode":true,"allowPurchaseItems":true,"displayStoreAddress":true,"useDefaultSearchConfig":{},"displayAddToCartOnFeaturedItems":true,"testMode":false,"displayCustomerSection":true,"defaultSearchConfigPath":{},"displaySearchBox":true,"displayCustomerAgreement":true,"displayContactUs":true}

still i cannot see the link...

**Comment by shopizer-ecommerce** [comment]
Make sure the session is expired for changes to take effect
